//! The bytes a consumer actually receives, pinned.
//!
//! # Why this exists separately from the round-trip tests
//!
//! `fusiform-protocol` asserts that the served types round-trip through JSON.
//! That proves the types are self-consistent and proves nothing about what a
//! consumer sees: a field renamed on both sides round-trips perfectly and
//! breaks every consumer.
//!
//! SUBC's framing of the fleet's payload rule has two halves — DECLARATIONS
//! SHARED, OUTPUTS PRODUCER-PINNED. The shared declaration is the protocol
//! crate. This file is the other half: a golden fixture of an actual served
//! payload, so a schema change fails fusiform's build until the fixture moves
//! with it.
//!
//! # The fixture is minted by the producer, never written by hand
//!
//! This repository's rule, learned from a defect in a sibling crate: a
//! hand-written fixture encodes its author's understanding of the format, so
//! when the parser and the fixture come from one belief in one commit, a
//! non-vacuous test certifies the bug. The fixture below is regenerated by
//! running the real serve path over a real store — `UPDATE_GOLDEN=1 cargo test
//! -p fusiform-module --test it golden_payload::` — and reviewed as a diff.
//!
//! Reviewing the diff is the point. A regenerated fixture that nobody reads is
//! a rubber stamp; the value is that a schema change shows up as a concrete
//! before/after in the payload a consumer parses, at review time.

use cortexkit_store_types::{Isolation, StorageBackend, StorageDescriptor};
use fusiform_core::normalize::normalize_models_dev;
use fusiform_core::{
    BoundaryKind, Correction, FieldId, ObservationOutcome, SourceId, Timestamp, TokenClass,
};
use fusiform_module::route::serve_tool_call;
use fusiform_store::ingest::plan_ingest;
use fusiform_store::{CatalogStore, FactKey, NewEra, NewObservation};

const UPSTREAM: &str = include_str!("../../../fusiform-core/fixtures/models-dev-excerpt.json");

/// A SYNTHETIC upstream document: one model publishing no `reasoning` key.
///
/// Inline rather than in the fixtures directory, deliberately. A file sitting
/// beside `models-dev-excerpt.json` would read as another real cut, and this is
/// not one — no model in today's live document omits the key. Keeping it here,
/// next to the reason, makes it impossible to mistake for measured data.
const UNKNOWN_REASONING: &str = r#"{
  "synthetic": {
    "id": "synthetic",
    "name": "Synthetic (not a real provider)",
    "models": {
      "unknown-reasoning": {
        "id": "unknown-reasoning",
        "name": "A model whose reasoning capability the upstream did not state",
        "limit": { "context": 128000, "output": 8192 }
      }
    }
  }
}"#;
/// A SYNTHETIC creator/reseller pair, so the fixture carries an INHERITED rate.
///
/// Without this the golden payload contains no `inherited_from` at all: the
/// marker is attached at serve time, and it needs a creator row publishing a
/// price for the same model id under a curated family. The real excerpt happens
/// to hold no such pair.
///
/// That absence matters because consumers PIN FROM THESE BYTES. ALF said so
/// explicitly, and a fixture that omits a served shape lets a wire change to it
/// land without reddening anything here — which is the entire job of a golden
/// payload.
///
/// `glm` -> `zai` is the real shipped mapping in model-creators.json, so this
/// exercises the actual table rather than a fixture that agrees with itself.
/// The creator is keyed `zai` because the lookup resolves on the PROVIDER KEY,
/// not the `id` field inside it — my first version keyed it
/// `synthetic-creator-zai` with `"id": "zai"` and produced no inheritance at
/// all, which is a fixture that would have passed while testing nothing. `zai`
/// is absent from the real excerpt (11 providers, checked), so there is no
/// collision to mask.
/// The reseller publishes NO rate at all, which is the population inheritance
/// serves after the stated_zero correction: a provider that publishes any rate
/// has a price card and is left alone.
const INHERITANCE_PAIR: &str = r#"{
  "zai": {
    "id": "zai",
    "name": "Synthetic zai entry (models are synthetic, the id is real)",
    "models": {
      "synthetic-glm": {
        "id": "synthetic-glm",
        "name": "A model whose weights the creator publishes and prices",
        "family": "glm",
        "open_weights": true,
        "limit": { "context": 128000, "output": 8192 },
        "cost": { "input": 0.075, "output": 0.25 }
      },
      "synthetic-glm-free": {
        "id": "synthetic-glm-free",
        "name": "A model whose creator states every dimension free",
        "family": "glm",
        "open_weights": true,
        "limit": { "context": 128000, "output": 8192 },
        "cost": { "input": 0, "output": 0 }
      }
    }
  },
  "synthetic-reseller": {
    "id": "synthetic-reseller",
    "name": "Synthetic reseller publishing no price (not a real provider)",
    "models": {
      "synthetic-glm": {
        "id": "synthetic-glm",
        "name": "The same weights served by someone who publishes no rate",
        "family": "glm",
        "open_weights": true,
        "limit": { "context": 128000, "output": 8192 }
      },
      "synthetic-glm-free": {
        "id": "synthetic-glm-free",
        "name": "Free weights served by someone who publishes no rate",
        "family": "glm",
        "open_weights": true,
        "limit": { "context": 128000, "output": 8192 }
      }
    }
  }
}"#;
const GOLDEN: &str = include_str!("../../fixtures/served-payloads.json");

/// The embedded models.dev seed. The plane cases copy real xAI and DeepSeek rows
/// out of it, because the fixture excerpt has neither provider.
const SEED: &str = include_str!("../../data/models-dev-seed.json");

/// The target of the shipped alias the fixture pins.
///
/// A curated alias serves only when its target is in the store, and the real
/// excerpt's `google` entry does not carry it. The row is cut from the embedded
/// seed rather than written here, so the aliased entry in the fixture shows
/// the facts a real target publishes — the same rule the rest of this file
/// follows for upstream data.
const ALIAS_TARGET: (&str, &str) = ("google", "gemini-3.8-flash");

/// The real upstream cut with the synthetic unknown-reasoning provider added.
///
/// Merged as JSON rather than concatenated as text, so a malformed splice fails
/// here instead of producing a document that parses into something unintended.
fn merged_upstream() -> String {
    let mut doc: serde_json::Value = serde_json::from_str(UPSTREAM).unwrap();
    let obj = doc.as_object_mut().expect("the upstream is an object");
    for src in [UNKNOWN_REASONING, INHERITANCE_PAIR] {
        let synthetic: serde_json::Value = serde_json::from_str(src).unwrap();
        for (k, v) in synthetic.as_object().expect("synthetic is an object") {
            assert!(
                obj.insert(k.clone(), v.clone()).is_none(),
                "a synthetic provider must not collide with a real one: {k}"
            );
        }
    }

    let seed: serde_json::Value = serde_json::from_str(SEED).expect("the seed parses");
    let target = seed[ALIAS_TARGET.0]["models"][ALIAS_TARGET.1].clone();
    assert!(
        target.is_object(),
        "the alias target must be in the embedded seed, or the alias cases \
         below pin a refusal instead of an aliased entry"
    );
    let models = obj
        .get_mut(ALIAS_TARGET.0)
        .and_then(|p| p.get_mut("models"))
        .and_then(|m| m.as_object_mut())
        .expect("the excerpt carries the target's provider");
    assert!(
        models.insert(ALIAS_TARGET.1.to_string(), target).is_none(),
        "the excerpt already carries the alias target; drop the splice"
    );
    serde_json::to_string(&doc).unwrap()
}

/// Keep plane-only provider splices out of the ordinary store: even an unused
/// model changes the counts published by catalog.status.
fn plane_store() -> (CatalogStore, tempfile::TempDir, Vec<(String, String)>) {
    let mut doc: serde_json::Value = serde_json::from_str(&merged_upstream()).unwrap();
    let seed: serde_json::Value = serde_json::from_str(SEED).unwrap();
    let mut cuts = Vec::new();
    for (provider, id) in [
        ("xai", "grok-4.20-0309-non-reasoning"),
        ("deepseek", "deepseek-flash"),
    ] {
        // Pin the cut, rather than picking the first matching id: a seed update
        // must not silently replace the tiered row this fixture exists to serve.
        let row = &seed[provider]["models"][id];
        assert!(row.is_object(), "the seed must carry {provider}/{id}");
        assert!(
            row["cost"]["input"].is_number(),
            "{provider}/{id} must publish input"
        );
        assert!(
            !row["cost"].to_string().contains("cache_write"),
            "{provider}/{id} must not publish cache_write, including tiers"
        );
        let mut cut = seed[provider].clone();
        cut["models"] = serde_json::json!({id: row});
        assert!(
            doc.as_object_mut()
                .unwrap()
                .insert(provider.into(), cut)
                .is_none(),
            "the excerpt already carries {provider}; drop the splice"
        );
        // A splice must never replace the row the ordinary alias fixture pins.
        assert_ne!((provider, id), ALIAS_TARGET);
        cuts.push((provider.to_string(), id.to_string()));
    }
    let dir = tempfile::tempdir().unwrap();
    let store = CatalogStore::open(&StorageDescriptor {
        module_id: "fusiform".into(),
        storage_namespace: "default".into(),
        isolation: Isolation::Module,
        backend: StorageBackend::Sqlite {
            path: dir.path().join("store.db").to_string_lossy().to_string(),
        },
    })
    .unwrap();
    let catalog = normalize_models_dev(serde_json::to_string(&doc).unwrap().as_bytes())
        .unwrap()
        .catalog;
    let plan = plan_ingest(&store, &catalog, Timestamp(1_000), BoundaryKind::Seed, None).unwrap();
    store.append_eras(&plan.eras).unwrap();
    (store, dir, cuts)
}

/// Both dispatch paths must apply a plane before filtering. Bulk cases carry
/// every provider row, not an artificial one-model store that hides neighbours.
fn plane_cases(cuts: &[(String, String)]) -> Vec<(String, serde_json::Value)> {
    let mut cases = Vec::new();
    for (filter, prefixes) in [
        ("unfiltered", None),
        ("rates", Some(vec!["rate."])),
        ("cache-write", Some(vec!["rate.cache_write"])),
        ("capabilities", Some(vec!["capability."])),
    ] {
        for path in ["named", "bulk"] {
            let mut args = serde_json::json!({"provider_id":"openai", "auth_method":"chatgpt"});
            if path == "named" {
                args["model_id"] = "gpt-5.6-luna".into();
            }
            if let Some(ref prefixes) = prefixes {
                args["fact_prefixes"] = serde_json::json!(prefixes);
            }
            cases.push((format!("chatgpt luna — {path}, {filter}"), args));
        }
    }
    cases.push((
        "chatgpt image — missing input target".into(),
        serde_json::json!({
            "provider_id":"openai", "model_id":"gpt-image-1", "auth_method":"chatgpt"
        }),
    ));
    cases.push((
        "apikey luna — published cache-write".into(),
        serde_json::json!({
            "provider_id":"openai", "model_id":"gpt-5.6-luna", "auth_method":"apikey"
        }),
    ));
    for (provider, id) in cuts {
        cases.push((
            format!("apikey {provider} — cache-write fill"),
            serde_json::json!({
                "provider_id":provider, "model_id":id, "auth_method":"apikey"
            }),
        ));
    }
    cases.push((
        "oauth anthropic — quota weights".into(),
        serde_json::json!({
            "provider_id":"anthropic", "auth_method":"oauth"
        }),
    ));
    for (label, args) in [
        (
            "refused — undeclared openai oauth",
            serde_json::json!({"provider_id":"openai", "auth_method":"oauth"}),
        ),
        (
            "refused — undeclared google antigravity",
            serde_json::json!({"provider_id":"google", "auth_method":"antigravity"}),
        ),
        (
            "refused — unknown auth",
            serde_json::json!({"provider_id":"openai", "auth_method":"bogus"}),
        ),
        (
            "refused — missing provider",
            serde_json::json!({"auth_method":"chatgpt"}),
        ),
        (
            "refused — historical plane",
            serde_json::json!({"provider_id":"openai", "auth_method":"chatgpt", "at_ms":1000}),
        ),
    ] {
        cases.push((label.into(), args));
    }
    cases
}

fn render_planes() -> String {
    let (store, _dir, cuts) = plane_store();
    let mut doc = serde_json::Map::new();
    for (label, args) in plane_cases(&cuts) {
        let request = serde_json::json!({"name":"catalog.get", "arguments":args});
        let body = serde_json::to_vec(&request).unwrap();
        let payload = match serve_tool_call(&store, &body) {
            Ok(response) => {
                assert!(
                    !label.starts_with("refused"),
                    "{label} unexpectedly served rows"
                );
                let mut value = serde_json::to_value(response).unwrap();
                value["resolved_at_ms"] = NOW_PLACEHOLDER.into();
                serde_json::json!({"request":request, "response":value})
            }
            Err(error) => {
                assert!(
                    label.starts_with("refused"),
                    "{label} must serve: {error:?}"
                );
                serde_json::json!({"request":request, "error":{"code":error.code, "message":error.message}})
            }
        };
        doc.insert(label, payload);
    }
    let mut text = serde_json::to_string_pretty(&doc).unwrap();
    text.push('\n');
    text
}

/// Consumers pin one document, while the two producers retain isolated stores.
fn render_all() -> String {
    let mut ordinary: serde_json::Value = serde_json::from_str(&render()).unwrap();
    let planes: serde_json::Value = serde_json::from_str(&render_planes()).unwrap();
    for (label, case) in planes.as_object().unwrap() {
        assert!(
            ordinary
                .as_object_mut()
                .unwrap()
                .insert(label.clone(), case.clone())
                .is_none(),
            "plane labels must not replace an ordinary golden case: {label}"
        );
    }
    let mut text = serde_json::to_string_pretty(&ordinary).unwrap();
    text.push('\n');
    text
}

fn non_plane_leaks(doc: &serde_json::Value) -> (usize, Vec<String>) {
    let mut checked = 0;
    let mut leaks = Vec::new();
    for (label, case) in doc.as_object().expect("golden cases are an object") {
        if case["request"]["arguments"].get("auth_method").is_some() {
            continue;
        }
        checked += 1;
        let response = &case["response"];
        let mut keys = std::collections::BTreeSet::new();
        collect_keys(response, &mut keys);
        let mut scanned = response.clone();
        // plan.prices legitimately uses state "not_established" for quota
        // values nobody has measured. Exempt only that state field from this
        // billing-data leak check, not a rate's reason "not_established" or the
        // forbidden plane and billing_rules keys anywhere in the response.
        if case["request"]["name"] == "plan.prices" {
            if let Some(prices) = scanned["prices"].as_array_mut() {
                for price in prices {
                    if price["quota_value"]["state"] == "not_established" {
                        price["quota_value"]
                            .as_object_mut()
                            .unwrap()
                            .remove("state");
                    }
                }
            }
        }
        let bytes = scanned.to_string();
        for forbidden in ["plane", "billing_rules"] {
            if keys.contains(forbidden) {
                leaks.push(format!("{label}: {forbidden}"));
            }
        }
        for forbidden in [r#""state":"billed_as""#, "not_established", "quota_proxy"] {
            if bytes.contains(forbidden) {
                leaks.push(format!("{label}: {forbidden}"));
            }
        }
    }
    (checked, leaks)
}

#[test]
fn every_non_plane_golden_case_has_no_plane_bytes() {
    // Check both saved bytes and live responses. A saved-only scan cannot see
    // plane logic accidentally applied to ordinary reads before regeneration.
    for text in [GOLDEN.to_string(), render()] {
        let doc = serde_json::from_str(&text).unwrap();
        let (checked, leaks) = non_plane_leaks(&doc);
        assert_eq!(checked, cases().len());
        assert!(
            leaks.is_empty(),
            "non-plane payload leaked plane-only bytes: {leaks:?}"
        );
    }
}

#[test]
fn planted_plane_bytes_in_an_ordinary_case_are_reported() {
    for response in [
        serde_json::json!({"plane":null}),
        serde_json::json!({"billing_rules":[]}),
        serde_json::json!({"rate":{"state":"billed_as", "key":"rate.input"}}),
        serde_json::json!({"rate":{"state":"unpriced", "reason":"not_established"}}),
        serde_json::json!({"rate":{"inherited_from":{"basis":"quota_proxy"}}}),
    ] {
        let doc = serde_json::json!({"ordinary":{"request":{"arguments":{}}, "response":response}});
        let (checked, leaks) = non_plane_leaks(&doc);
        assert_eq!(checked, 1);
        assert_eq!(
            leaks.len(),
            1,
            "the scan must catch each forbidden shape independently"
        );
    }
}

#[test]
fn quota_refusals_do_not_exempt_plan_prices_from_the_plane_fence() {
    let mut doc = serde_json::json!({"plans": {
        "request":{"name":"plan.prices", "arguments":{}},
        "response":{"prices":[{"quota_value":{"state":"not_established", "refusal_reason":"no measured account", "review_by_ms":1000}}]}
    }});
    let (checked, leaks) = non_plane_leaks(&doc);
    assert_eq!(checked, 1);
    assert!(
        leaks.is_empty(),
        "a legitimate quota refusal is not a billing-plane leak: {leaks:?}"
    );
    doc["plans"]["response"]["rate"] =
        serde_json::json!({"state":"unpriced", "reason":"not_established"});
    assert_eq!(non_plane_leaks(&doc).1, ["plans: not_established"]);
    doc["plans"]["response"]["prices"][0]["quota_value"]["plane"] = serde_json::Value::Null;
    assert!(non_plane_leaks(&doc)
        .1
        .contains(&"plans: plane".to_string()));
}

fn assert_rule(response: &serde_json::Value, model: &str, key: &str, state: &str, source: &str) {
    let rules = response["billing_rules"]
        .as_array()
        .expect("rules are disclosed");
    let matching: Vec<_> = rules
        .iter()
        .filter(|rule| rule["model"] == model && rule["fact_key"] == key)
        .collect();
    assert_eq!(
        matching.len(),
        1,
        "exactly one disclosure for {model}/{key}"
    );
    assert_eq!(
        *matching[0],
        serde_json::json!({
            "model":model, "fact_key":key, "state":state, "as_class":"input",
            "source_ref":source, "established_by":"fusiform",
            "established_at_ms":1791331200000_i64, "review_by_ms":1796515200000_i64
        })
    );
}

#[test]
fn chatgpt_named_and_bulk_cases_apply_the_plane_before_each_filter() {
    let doc: serde_json::Value = serde_json::from_str(&render_planes()).unwrap();
    let source = "https://help.openai.com/en/articles/20001106";
    for path in ["named", "bulk"] {
        for filter in ["unfiltered", "rates", "cache-write", "capabilities"] {
            let label = format!("chatgpt luna — {path}, {filter}");
            let response = &doc[&label]["response"];
            assert_eq!(
                response["plane"],
                serde_json::json!({
                    "provider_id":"openai", "auth_method":"chatgpt", "kind":"quota_proxy",
                    "source_ref":source, "review_by_ms":1796515200000_i64
                }),
                "{label}"
            );
            let models = response["models"].as_object().unwrap();
            assert_eq!(models.len(), if path == "named" { 1 } else { 2 });
            let row = models["openai/gpt-5.6-luna"].as_object().unwrap();
            assert!(!row.is_empty(), "{label} must serve the requested plane");
            assert!(!row.keys().any(|key| key.contains(".mode.")), "{label}");
            if filter == "capabilities" {
                assert!(
                    row.keys().all(|key| key.starts_with("capability.")),
                    "{label}"
                );
                assert!(
                    !response.as_object().unwrap().contains_key("billing_rules"),
                    "{label}"
                );
                continue;
            }
            if filter == "rates" {
                assert!(row.keys().all(|key| key.starts_with("rate.")), "{label}");
            }
            if filter == "cache-write" {
                assert!(
                    row.keys().all(|key| key.starts_with("rate.cache_write")),
                    "{label}"
                );
            }
            for suffix in ["", ".above_context.272000"] {
                let key = format!("rate.cache_write{suffix}");
                assert_eq!(
                    row[&key],
                    serde_json::json!({"state":"billed_as", "key":format!("rate.input{suffix}")}),
                    "{label}"
                );
                assert_rule(response, "openai/gpt-5.6-luna", &key, "billed_as", source);
                if filter != "cache-write" {
                    for class in ["input", "cache_read", "output"] {
                        let rate = &row[&format!("rate.{class}{suffix}")];
                        assert_eq!(rate["state"], "priced", "{label}");
                        assert_eq!(
                            rate["inherited_from"],
                            serde_json::json!({
                                "provider_id":"openai", "family":"gpt-luna", "basis":"quota_proxy"
                            }),
                            "{label}: a rate-only filter must retain the real family"
                        );
                    }
                }
            }
            let rate_count = row.keys().filter(|key| key.starts_with("rate.")).count();
            assert_eq!(
                rate_count,
                if filter == "cache-write" { 2 } else { 8 },
                "{label}"
            );
            let rules = response["billing_rules"].as_array().unwrap();
            assert_eq!(rules.len(), if path == "named" { 2 } else { 3 });
            for rule in rules {
                let served = &models[rule["model"].as_str().unwrap()];
                assert!(
                    served.get(rule["fact_key"].as_str().unwrap()).is_some(),
                    "a narrowed-away fact must not disclose a rule: {label}"
                );
            }
        }
    }
}

#[test]
fn plane_cases_pin_missing_targets_published_api_prices_and_upstream_fills() {
    let doc: serde_json::Value = serde_json::from_str(&render_planes()).unwrap();
    let response = &doc["chatgpt image — missing input target"]["response"];
    assert_eq!(
        response["models"]["openai/gpt-image-1"]["rate.cache_write"],
        serde_json::json!({"state":"unpriced", "reason":"not_established"})
    );
    assert_eq!(response["billing_rules"].as_array().unwrap().len(), 1);
    assert_rule(
        response,
        "openai/gpt-image-1",
        "rate.cache_write",
        "not_established",
        "https://help.openai.com/en/articles/20001106",
    );

    let response = &doc["apikey luna — published cache-write"]["response"];
    assert_eq!(
        response["plane"],
        serde_json::json!({"provider_id":"openai", "auth_method":"apikey", "kind":"upstream"})
    );
    assert!(response.get("billing_rules").is_none());
    let row = response["models"]["openai/gpt-5.6-luna"]
        .as_object()
        .unwrap();
    for (key, units) in [
        ("rate.cache_write", 250000000),
        ("rate.cache_write.above_context.272000", 500000000),
    ] {
        assert_eq!(row[key]["state"], "priced");
        assert_eq!(row[key]["units"], units);
    }
    assert!(
        row.keys().any(|key| key.contains(".mode.")),
        "API mode prices stay served"
    );
    for (key, value) in row.iter().filter(|(key, _)| key.starts_with("rate.")) {
        assert!(
            value.get("inherited_from").is_none(),
            "API rate must not be marked: {key}"
        );
    }

    for (provider, source) in [
        (
            "xai",
            "https://docs.x.ai/developers/advanced-api-usage/prompt-caching/usage-and-pricing",
        ),
        (
            "deepseek",
            "https://api-docs.deepseek.com/api/create-chat-completion",
        ),
    ] {
        let response = &doc[format!("apikey {provider} — cache-write fill")]["response"];
        assert_eq!(
            response["plane"],
            serde_json::json!({
                "provider_id":provider, "auth_method":"apikey", "kind":"upstream",
                "source_ref":source, "review_by_ms":1796515200000_i64
            })
        );
        let models = response["models"].as_object().unwrap();
        assert_eq!(models.len(), 1);
        let (model, row) = models.iter().next().unwrap();
        let row = row.as_object().unwrap();
        let inputs: Vec<_> = row
            .keys()
            .filter(|key| *key == "rate.input" || key.starts_with("rate.input.above_context."))
            .collect();
        assert!(
            !inputs.is_empty(),
            "the fill must have a published input target"
        );
        // The real xAI cut publishes a tier; DeepSeek's cut publishes only a
        // base price. Requiring the measured counts keeps the suffix assertion
        // from becoming vacuous if a future cut loses its tier.
        assert_eq!(inputs.len(), if provider == "xai" { 2 } else { 1 });
        assert_eq!(
            response["billing_rules"].as_array().unwrap().len(),
            inputs.len()
        );
        for input in inputs {
            let key = input.replacen("rate.input", "rate.cache_write", 1);
            assert_eq!(
                row[&key],
                serde_json::json!({"state":"billed_as", "key":input})
            );
            assert_rule(response, model, &key, "billed_as", source);
        }
    }
}

#[test]
fn anthropic_oauth_marks_every_served_rate_and_drops_modes() {
    let doc: serde_json::Value = serde_json::from_str(&render_planes()).unwrap();
    let response = &doc["oauth anthropic — quota weights"]["response"];
    assert_eq!(
        response["plane"],
        serde_json::json!({
            "provider_id":"anthropic", "auth_method":"oauth", "kind":"quota_proxy",
            "source_ref":"https://support.anthropic.com/en/articles/9797557", "review_by_ms":1796515200000_i64
        })
    );
    assert!(response.get("billing_rules").is_none());
    let mut rates = 0;
    for row in response["models"].as_object().unwrap().values() {
        for (key, value) in row
            .as_object()
            .unwrap()
            .iter()
            .filter(|(key, _)| key.starts_with("rate."))
        {
            rates += 1;
            assert!(!key.contains(".mode."));
            assert_eq!(value["inherited_from"]["basis"], "quota_proxy");
        }
    }
    assert!(rates > 0, "oauth must serve real quota weights");
}

#[test]
fn plane_refusal_cases_never_fall_back_to_api_rows() {
    let doc: serde_json::Value = serde_json::from_str(&render_planes()).unwrap();
    for (label, code, needles) in [
        (
            "refused — undeclared openai oauth",
            "no_coverage",
            vec!["openai", "oauth"],
        ),
        (
            "refused — undeclared google antigravity",
            "no_coverage",
            vec!["google", "antigravity"],
        ),
        (
            "refused — unknown auth",
            "bad_request",
            vec!["bogus", "apikey", "chatgpt", "oauth", "antigravity"],
        ),
        (
            "refused — missing provider",
            "bad_request",
            vec!["provider_id"],
        ),
        (
            "refused — historical plane",
            "no_coverage",
            vec!["current-only", "at_ms"],
        ),
    ] {
        let case = &doc[label];
        assert!(
            case.get("response").is_none(),
            "{label} must not serve rows"
        );
        assert_eq!(case["error"]["code"], code, "{label}");
        let message = case["error"]["message"].as_str().unwrap();
        for needle in needles {
            assert!(
                message.contains(needle),
                "{label}: {message} must name {needle}"
            );
        }
    }
}

/// A store whose contents are fixed, so the payload is reproducible.
///
/// Every instant IN THE STORE is a literal, so nothing about the data moves
/// between runs. One field in one payload still does: a read with no `at_ms`
/// resolves to now by definition, and its `resolved_at_ms` is a wall clock
/// reading. That case substitutes a placeholder — and the point-in-time case
/// below pins the same field exactly, so the field's spelling and type are
/// covered while its unpinnable value is not pretended to be fixed.
///
/// This is narrower than it first looked. The initial version of this file
/// claimed every instant was a literal, which was false for exactly that one
/// read, and the test failed on its second run.
fn store() -> (CatalogStore, tempfile::TempDir) {
    let dir = tempfile::tempdir().unwrap();
    let store = CatalogStore::open(&StorageDescriptor {
        module_id: "fusiform".to_string(),
        storage_namespace: "default".to_string(),
        isolation: Isolation::Module,
        backend: StorageBackend::Sqlite {
            path: dir.path().join("store.db").to_string_lossy().to_string(),
        },
    })
    .unwrap();

    // A seed, so the catalog exists.
    store
        .record_observation(&NewObservation {
            source: SourceId::ModelsDev,
            observed_at: Timestamp(1_000),
            outcome: ObservationOutcome::Seeded,
            normalized_hash: Some("seed-hash".into()),
            raw_hash: Some("seed-raw".into()),
            etag: None,
            duration_ms: Some(12),
            detail: None,
        })
        .unwrap();
    // ONE document, not two.
    //
    // A second `plan_ingest` at the same instant would diff the synthetic
    // document against the store and tombstone every model from the first --
    // ingest treats "absent from this document" as a withdrawal, which is
    // correct and is exactly why a fixture must present one document rather
    // than two. Caught by the schema's uniqueness constraint on first run.
    let catalog = normalize_models_dev(merged_upstream().as_bytes())
        .unwrap()
        .catalog;
    let plan = plan_ingest(&store, &catalog, Timestamp(1_000), BoundaryKind::Seed, None).unwrap();
    store.append_eras(&plan.eras).unwrap();

    // A model whose reasoning capability is UNKNOWN, from a document that is
    // deliberately synthetic and labelled as such.
    //
    // Every other row in this fixture comes from a real upstream cut, which is
    // this repository's rule: a hand-written fixture encodes its author's
    // understanding of the format. This one cannot, and the reason is worth
    // stating rather than hiding. Measured on the live document today: all
    // 6,291 models publish the `reasoning` key, so ABSENT does not occur
    // upstream and cannot be cut from it.
    //
    // It is pinned anyway because the null is the whole point of BROCA's
    // parser fix — `as_bool()` returns None on a JSON null, so absent, false
    // and null all collapse to false, and a capable model silently stops
    // reasoning. Their deny-drift test vendors THIS fixture, so without a null
    // row their check cannot cover the case it exists for.
    //
    // The alternative was to leave the wire shape unpinned until the upstream
    // produces one, which means the first real occurrence is also the first
    // test of the path.

    // A SECOND INGEST WITH ONE RATE WITHDRAWN, so the fixture carries an
    // `unpriced` rate produced by the ingest path rather than written by hand.
    //
    // `unpriced/missing_rate` is a TOMBSTONE: the upstream described the model
    // and stopped publishing a rate it used to publish. 153 eras in the live
    // catalog carry it today, so it is an ordinary served state rather than an
    // edge case — and the one a consumer most needs to get right, because a
    // withdrawn rate is emphatically NOT zero. A decoder that defaults it
    // charges nothing for a model that bills.
    //
    // Generated by `plan_ingest` rather than appended as a literal, for the
    // reason the inheritance case exists: a hand-written value pins what I
    // BELIEVE the producer emits, and the fixture's whole job is to pin what it
    // ACTUALLY emits. If `withdrawal_value` changes, this reddens; a literal
    // would not.
    let withdrawn = {
        let mut doc: serde_json::Value =
            serde_json::from_str(&merged_upstream()).expect("the merged upstream parses");
        let cost = doc["zhipuai"]["models"]["glm-4.5-flash"]["cost"]
            .as_object_mut()
            .expect("glm-4.5-flash has a cost object");
        assert!(
            cost.remove("cache_write").is_some(),
            "the key being withdrawn must exist first, or this ingest is a no-op \
             and the fixture silently loses the tombstone"
        );

        // A WHOLE MODEL withdrawn as well, so the fixture carries a RETIRED
        // row. The `retired` array was added for a consumer whose roster went
        // stale on an upstream rename, and it appeared nowhere in these bytes
        // — the field exists precisely so a named read of a retired model is
        // distinguishable from a read of an unknown one, and neither shape was
        // pinned.
        let models = doc["poe"]["models"]
            .as_object_mut()
            .expect("poe publishes models");
        assert!(
            models.remove("google/veo-3").is_some(),
            "the model being withdrawn must exist first, or the retirement is a \
             no-op and the case below reads an unknown model instead"
        );
        assert!(
            !models.is_empty(),
            "the provider must keep a model, or this withdraws the PROVIDER too \
             and the read refuses for a different reason than the one pinned"
        );
        serde_json::to_string(&doc).expect("the edited document serialises")
    };
    let obs = store
        .record_observation(&NewObservation {
            source: SourceId::ModelsDev,
            observed_at: Timestamp(1_500),
            outcome: ObservationOutcome::Changed { snapshot_seq: 2 },
            normalized_hash: Some("withdrawal-hash".into()),
            raw_hash: Some("withdrawal-raw".into()),
            etag: None,
            duration_ms: Some(210),
            detail: None,
        })
        .unwrap();
    let catalog = normalize_models_dev(withdrawn.as_bytes())
        .expect("the withdrawn document normalises")
        .catalog;
    let plan = plan_ingest(
        &store,
        &catalog,
        Timestamp(1_500),
        BoundaryKind::Observed,
        Some(obs),
    )
    .unwrap();
    assert!(
        plan.eras
            .iter()
            .any(|e| e.value_json.contains("missing_rate")),
        "the withdrawal must produce a tombstone, or the fixture pins nothing \
         new: got {} eras",
        plan.eras.len()
    );
    store.append_eras(&plan.eras).unwrap();

    // THE CURATED PLAN PRICES, applied exactly as boot applies them.
    //
    // Without this the whole `plan.prices` tool is absent from the fixture: I
    // shipped it and never pinned its wire shape, so a change to `prices`,
    // `unit_policy` or `tier_vocabulary` would redden nothing here. That is the
    // same gap the rate states had — a surface consumers pin from, covering
    // less than the wire carries.
    //
    // Applied through `store_rows(rows())` rather than hand-built, so the
    // fixture pins what the SHIPPED FILE produces. A synthetic row would pin a
    // shape nobody serves, and the curated file is the artifact under review.
    let plan_rows = fusiform_module::plan_prices::store_rows(fusiform_module::plan_prices::rows());
    assert!(
        !plan_rows.is_empty(),
        "the curated file must yield rows, or the plan.prices cases below pin an \
         empty answer and prove nothing"
    );
    store.append_plan_prices(&plan_rows).unwrap();

    // A failed poll, so the status payload carries a failure class. An
    // all-successful history would leave the fields a consumer reads during an
    // incident unpinned.
    store
        .record_observation(&NewObservation {
            source: SourceId::ModelsDev,
            observed_at: Timestamp(2_000),
            outcome: ObservationOutcome::Failed {
                class: fusiform_core::FailureClass::HttpStatus,
            },
            normalized_hash: None,
            raw_hash: None,
            etag: None,
            duration_ms: Some(87),
            detail: Some("upstream returned 503".into()),
        })
        .unwrap();

    // A correction, so the withheld list and the correction extent are pinned.
    // These are the fields a consumer needs exactly when something is wrong,
    // which is when nobody is regenerating fixtures.
    store
        .append_eras(&[NewEra {
            source: SourceId::ModelsDev,
            provider_id: "anthropic".into(),
            model_id: "claude-sonnet-4-5".into(),
            fact_key: FactKey::rate(TokenClass::Input),
            value_json: r#"{"state":"priced","currency":"USD","exponent":9,"units":3000000000}"#
                .into(),
            boundary_at: Timestamp(9_000),
            boundary_kind: BoundaryKind::Corrected(Correction {
                fields: vec![FieldId::Rate {
                    class: TokenClass::Input,
                }],
                affected_from: Timestamp(3_000),
                affected_until: Timestamp(9_000),
                reason: "normalizer scaled tiered rates by 1000x".to_string(),
            }),
            observation_id: None,
        }])
        .unwrap();

    (store, dir)
}

/// The calls whose payloads are pinned, each with why it is here.
///
/// # Each case exists for a DISTINCT SHAPE, and consolidating them is the risk
///
/// Two fences below check that every response field and every `SERVED_FACTS`
/// key appears somewhere in the fixture. Both are key-level: they ask whether a
/// name is present, not whether its shape was separately produced.
///
/// So a well-meaning consolidation — folding three cases into one model that
/// happens to carry all three keys — keeps both fences green while the shapes
/// stop being independently pinned.
///
/// I cited a peer's repository here as a second instance. They then MEASURED it
/// and it was not one: dropping a key from the fixture I described fails two of
/// their tests, because the event those tests price carries every role, so a
/// missing key leaves a measurement unpriced. Their fixture was fenced by a
/// property nobody had written down as a fence.
///
/// Removed rather than corrected in place, because the claim was doing work it
/// could not support -- a second instance makes a risk look general, and this
/// one is mine alone until someone finds another. Second time in this file I
/// have overstated a coupling in another repository; the note at the
/// inheritance case below is the first.
///
/// The rule, stated because no fence here can enforce it: A CASE EARNS ITS
/// PLACE BY THE SHAPE IT PRODUCES, not by the keys it happens to contain. If
/// two cases look redundant, check what each one's comment says it is for
/// before merging them — the reasons are in the cases rather than in a list
/// somewhere, precisely so this question is answerable at the point of
/// temptation.
fn cases() -> Vec<(&'static str, String)> {
    vec![
        (
            "catalog.get — one model, current",
            r#"{"name":"catalog.get","arguments":{"provider_id":"anthropic","model_id":"claude-sonnet-4-5"}}"#.to_string(),
        ),
        (
            // Inside the corrected interval: exercises the withheld list, which
            // is the shape a consumer sees when fusiform refuses a fact.
            "catalog.get — inside a corrected interval",
            r#"{"name":"catalog.get","arguments":{"provider_id":"anthropic","model_id":"claude-sonnet-4-5","at_ms":5000}}"#.to_string(),
        ),
        (
            // A PUBLISHED ZERO, which is a price rather than an absence: the
            // provider states this dimension is free. Distinct on the wire from
            // `unpriced` below, and collapsing them is the defect this
            // vocabulary exists to prevent — one means "costs nothing", the
            // other means "nobody said".
            //
            // Pinned because consumers pin from these bytes. Until now the
            // fixture carried only `priced`, so a consumer building a decoder
            // against it would never meet this state, and the first row that
            // carried it would land on a default arm.
            "catalog.get — a rate published as zero",
            r#"{"name":"catalog.get","arguments":{"provider_id":"greenpt","model_id":"green-s","fact_prefixes":["rate."]}}"#.to_string(),
        ),
        (
            // NO BASE COST OBJECT UPSTREAM, but a priced `fast` mode: the row
            // carries `rate.<class>.mode.fast` and no base `rate.<class>` at
            // all. Five live rows have this shape. A consumer must read the
            // missing base keys as unpriced, not as zero, and must not price a
            // base-mode request from the mode's rates.
            //
            // This case used to pin a row with no rate facts whatsoever; the
            // same row now serves its mode rates, which is the shape worth
            // pinning, and a row with no rates at all is still pinned by the
            // unknown-reasoning case below.
            "catalog.get — a model priced only in a mode, with no base rate",
            r#"{"name":"catalog.get","arguments":{"provider_id":"anyapi","model_id":"anthropic/claude-opus-4-6"}}"#.to_string(),
        ),
        (
            // MODE RATES BESIDE BASE RATES, from a real row: OpenAI
            // gpt-5.6-luna publishes a base card, context tiers, a priced
            // `fast` mode (service_tier priority upstream) and a `pro` mode
            // with no cost. The rate plane shows `rate.<class>.mode.fast` next
            // to the base and tiered keys, in the base rates' value shape, and
            // NOTHING for `pro`: a mode without a published price has no key,
            // which a consumer reads as unpriced in that mode. The request
            // bytes that select either mode appear nowhere.
            "catalog.get — mode rates beside base rates, and a mode with no price",
            r#"{"name":"catalog.get","arguments":{"provider_id":"openai","model_id":"gpt-5.6-luna","fact_prefixes":["rate."]}}"#.to_string(),
        ),
        (
            // The WITHDRAWN rate, tombstoned as `unpriced/missing_rate` by the
            // second ingest above. Completes the rate vocabulary in this
            // fixture: `priced`, `stated_zero`, `unpriced`, and `inherited_from`
            // all appear in bytes a consumer can pin.
            "catalog.get — a rate the upstream withdrew",
            r#"{"name":"catalog.get","arguments":{"provider_id":"zhipuai","model_id":"glm-4.5-flash","fact_prefixes":["rate."]}}"#.to_string(),
        ),
        (
            // The whole `plan.prices` surface: priced tiers, a REFUSAL row, the
            // unit policy and the tier vocabulary. Every one of these was
            // unpinned until now.
            //
            // The refusal matters most — `openai/pro` carries no price because
            // the API plan string does not resolve to a vendor tier, and a
            // consumer that reads a missing price as free bills nothing for a
            // subscription that costs money.
            "plan.prices — every curated row",
            r#"{"name":"plan.prices","arguments":{}}"#.to_string(),
        ),
        (
            // A NAMED READ OF A RETIRED MODEL. The model is gone from the
            // upstream, so `models` is empty and `retired` names it with the
            // instant it went.
            //
            // Distinct from a read of an UNKNOWN model, which refuses with
            // no_coverage. Collapsing the two is what sent a consumer hunting a
            // deletion when the upstream had renamed a provider, and this is
            // the shape that tells them apart.
            "catalog.get — a named read of a retired model",
            r#"{"name":"catalog.get","arguments":{"provider_id":"poe","model_id":"google/veo-3"}}"#.to_string(),
        ),
        (
            // A READ INSIDE AN UNOBSERVED WINDOW, which populates `uncertain`.
            //
            // The withdrawal landed at t=1500 and the observation before it was
            // t=1000, so at t=1200 the store knows the value it served and does
            // NOT know whether it still held — the change could have happened
            // either side of the instant asked for.
            //
            // Unpinned until now, and it is the field a consumer needs to
            // reconstruct a past decision honestly: flattening the bracket to a
            // point value turns "nobody was watching" into a confident answer.
            "catalog.get — an instant inside an unobserved window",
            r#"{"name":"catalog.get","arguments":{"provider_id":"zhipuai","model_id":"glm-4.5-flash","at_ms":1200,"fact_prefixes":["rate."]}}"#.to_string(),
        ),
        (
            // `rate.reasoning`, the one served fact key absent from every other
            // case here — found by asking the fact-key question the response
            // field fence does not cover.
            //
            // Worth its own case rather than incidental coverage: only 166 of
            // 6,213 reasoning-capable models in the live catalog carry this key,
            // so a consumer is unlikely to meet one by accident and very likely
            // to meet one eventually. 115 of those restate the model's output
            // rate, and 29 publish a genuinely different number — alibaba bills
            // reasoning at 2.5x to 3.3x output, perplexity's sonar at 0.38x — so
            // a decoder that defaults this key to the output rate is wrong in
            // BOTH directions and the errors cancel in aggregate.
            "catalog.get — a model that prices reasoning separately",
            r#"{"name":"catalog.get","arguments":{"provider_id":"nebius","model_id":"Qwen/Qwen3-Next-80B-A3B-Thinking","fact_prefixes":["rate."]}}"#.to_string(),
        ),
        (
            // `capability.reasoning_options` published as `[]`: the upstream
            // states the model takes NO reasoning settings. A different claim
            // from the `null` the unknown-reasoning case below carries (the
            // upstream said nothing) and from the populated list on the first
            // case, and a consumer that collapses `[]` and `null` either
            // refuses a model it knows nothing about or sends settings to one
            // that was stated to take none. Scoped to the capability plane so
            // this case earns its place by that one shape.
            "catalog.get — a model stating it takes no reasoning options",
            r#"{"name":"catalog.get","arguments":{"provider_id":"nebius","model_id":"Qwen/Qwen3-Next-80B-A3B-Thinking","fact_prefixes":["capability."]}}"#.to_string(),
        ),
        (
            "catalog.history — a corrected fact",
            r#"{"name":"catalog.history","arguments":{"provider_id":"anthropic","model_id":"claude-sonnet-4-5","fact_key":"rate.input"}}"#.to_string(),
        ),
        (
            // The wire shape of an UNKNOWN capability, which is the case
            // BROCA's parser fix is entirely about. Pinned here because the
            // null was proven at the core boundary and never proven to survive
            // to the wire -- correct at one layer, unverified at the next.
            "catalog.get — a model whose reasoning capability is unknown",
            r#"{"name":"catalog.get","arguments":{"provider_id":"synthetic","model_id":"unknown-reasoning"}}"#.to_string(),
        ),
        (
            // An INHERITED rate, a shape absent everywhere else in this fixture.
            // The reseller publishes no rate of its own, so every rate on this
            // row is borrowed from the creator and carries `inherited_from`.
            //
            // Pinned because consumers pin from these bytes: with no case
            // requesting this row, the marker never appears in the golden
            // payload and a wire change to it lands without reddening anything.
            // Astrocyte's inherited-rate test was SEEDED FROM this case
            // (astrocyte aba2219): they copied the marked row's bytes into a
            // literal, so the case is an origin rather than a dependency.
            // Renaming or rearranging it does not break them — their test holds
            // its own copy and asserts about the WIRE SHAPE, not about any row
            // in this store.
            //
            // The note exists so a future reader knows where those bytes came
            // from, which is a question that has no answer from their side. My
            // first version of this comment said "pins byte-for-byte" and
            // warned that an edit here breaks a test there; ASTRO corrected it.
            // An overstated coupling is its own defect — it makes a reader
            // afraid of an edit that is actually safe, and a warning nobody can
            // verify is indistinguishable from one that is wrong.
            "inherited rate",
            r#"{"name":"catalog.get","arguments":{"provider_id":"synthetic-reseller","model_id":"synthetic-glm"}}"#.to_string(),
        ),
        (
            // A BORROWED ZERO: the creator states the model free and the
            // reseller publishes nothing, so the reseller's rates are
            // `stated_zero` carrying `inherited_from`. The only case where the
            // marker rides on a non-priced state, which is the shape a consumer
            // decoding through `RateValue` would otherwise read as the reseller
            // itself stating the model is free.
            "inherited stated zero",
            r#"{"name":"catalog.get","arguments":{"provider_id":"synthetic-reseller","model_id":"synthetic-glm-free","fact_prefixes":["rate."]}}"#.to_string(),
        ),
        (
            // The creator's own row, as the CONTROL: it publishes its own price
            // and must carry no marker. Without this arm the fixture cannot
            // tell "inheritance works" from "everything is marked inherited".
            "creator row, unmarked",
            r#"{"name":"catalog.get","arguments":{"provider_id":"zai","model_id":"synthetic-glm"}}"#.to_string(),
        ),
        (
            // A CURATED ALIAS: a route's id that models.dev does not publish,
            // served with its target's facts under the alias key. The only
            // case producing `aliased` and an `inherited_from` carrying
            // `model_id` with `basis: "alias"` — the marker that says a price
            // is the target's API list price and not the route's own.
            "catalog.get — a curated alias",
            r#"{"name":"catalog.get","arguments":{"provider_id":"google","model_id":"antigravity-gemini-3.8-flash"}}"#.to_string(),
        ),
        (
            // History of an alias id: no eras, because fusiform never observed
            // the id, and the target named so a consumer knows whose history
            // to ask for. Distinct from the inherited-rate explanation, which
            // names another PROVIDER for the same model id.
            "catalog.history — an alias id names its target",
            r#"{"name":"catalog.history","arguments":{"provider_id":"google","model_id":"antigravity-gemini-3.8-flash","fact_key":"rate.input"}}"#.to_string(),
        ),
        (
            "catalog.status",
            r#"{"name":"catalog.status","arguments":{"polls":3}}"#.to_string(),
        ),
    ]
}

/// The one field that cannot be pinned, and what stands in for it.
const NOW_PLACEHOLDER: i64 = -1;

fn render() -> String {
    let (store, _dir) = store();
    let mut doc = serde_json::Map::new();
    for (label, body) in cases() {
        let response = serve_tool_call(&store, body.as_bytes())
            .unwrap_or_else(|e| panic!("{label} must serve: {e:?}"));
        let mut value = serde_json::to_value(&response).unwrap();

        // A read with no `at_ms` resolves to wall-clock now. Substituted rather
        // than dropped: the KEY stays in the fixture, so a rename or a type
        // change still shows up as a diff, and only the unpinnable number is
        // replaced. Asserted separately below that the real value is sane.
        if !body.contains("at_ms") {
            if let Some(resolved) = value.get_mut("resolved_at_ms") {
                *resolved = serde_json::json!(NOW_PLACEHOLDER);
            }
        }

        doc.insert(
            label.to_string(),
            serde_json::json!({
                "request": serde_json::from_str::<serde_json::Value>(&body).unwrap(),
                "response": value,
            }),
        );
    }
    let mut text = serde_json::to_string_pretty(&serde_json::Value::Object(doc)).unwrap();
    text.push('\n');
    text
}

/// The substituted field really does carry a current instant.
///
/// The placeholder above keeps the fixture stable, and on its own it would let
/// `resolved_at_ms` become anything at all — zero, a constant, last week —
/// without any test noticing. This checks the real value.
#[test]
fn a_current_read_resolves_to_an_instant_near_now() {
    let (store, _dir) = store();
    let before = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_millis() as i64;

    let response = serve_tool_call(
        &store,
        br#"{"name":"catalog.get","arguments":{"provider_id":"anthropic","model_id":"claude-sonnet-4-5"}}"#,
    )
    .unwrap();
    let value = serde_json::to_value(&response).unwrap();
    let resolved = value
        .get("resolved_at_ms")
        .and_then(|v| v.as_i64())
        .expect("a current read reports the instant it resolved to");

    let after = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_millis() as i64;

    assert!(
        resolved >= before && resolved <= after,
        "a current read must resolve to now: got {resolved}, expected between \
         {before} and {after}"
    );
}

/// The served payloads have not changed.
#[test]
fn the_served_payloads_match_the_golden_fixture() {
    let rendered = render_all();

    if std::env::var("UPDATE_GOLDEN").is_ok() {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/fixtures/served-payloads.json");
        std::fs::write(path, &rendered).unwrap();
        eprintln!("golden fixture regenerated at {path} — review the diff");
        return;
    }

    if rendered != GOLDEN {
        // The diff rather than the whole document: a 200-line dump of two
        // similar payloads is unreadable, and the changed lines are the point.
        let mut differing = Vec::new();
        for (i, (a, b)) in GOLDEN.lines().zip(rendered.lines()).enumerate() {
            if a != b {
                differing.push(format!("  line {}:\n    was: {a}\n    now: {b}", i + 1));
            }
        }
        if GOLDEN.lines().count() != rendered.lines().count() {
            differing.push(format!(
                "  line count: was {}, now {}",
                GOLDEN.lines().count(),
                rendered.lines().count()
            ));
        }
        panic!(
            "the served payload changed. A consumer parses these bytes.\n\n{}\n\n\
             If the change is intended, regenerate with:\n  \
             UPDATE_GOLDEN=1 cargo test -p fusiform-module --test it golden_payload::\n\
             and bump fusiform-protocol's version — CI enforces that separately.",
            differing.join("\n")
        );
    }
}

/// The fixture is not empty, and carries the shapes it exists to pin.
///
/// A golden test whose fixture lost its interesting cases still passes, because
/// it compares the file to itself. This asserts the file contains the shapes
/// that motivated it — so a regeneration that silently dropped the correction
/// path fails here rather than passing quietly.
#[test]
fn the_fixture_pins_the_shapes_it_exists_for() {
    for needle in [
        // A priced rate with its explicit exponent and currency.
        r#""state": "priced""#,
        r#""exponent": 9"#,
        r#""currency": "USD""#,
        // The withheld list and a correction's extent and reason.
        r#""withheld""#,
        r#""affected_from_ms""#,
        "normalizer scaled tiered rates by 1000x",
        // A failure class on a recorded poll.
        r#""failure_class": "http_status""#,
        r#""outcome": "failed""#,
        // An observation window on an era.
        r#""boundary_kind""#,
        // The placeholder for the one unpinnable field. If this vanishes, the
        // substitution stopped happening and the fixture will churn.
        r#""resolved_at_ms": -1"#,
        // A curated alias and the marker on a price borrowed through it.
        r#""aliased""#,
        r#""basis": "alias""#,
        // Current-only plane variants and both provenance disclosures.
        r#""plane""#,
        r#""billing_rules""#,
        r#""state": "billed_as""#,
        r#""reason": "not_established""#,
        r#""basis": "quota_proxy""#,
    ] {
        assert!(
            GOLDEN.contains(needle),
            "the golden fixture no longer pins {needle:?} — a regeneration \
             dropped a case this file exists to hold"
        );
    }
}

/// Every field of every READ response appears somewhere in the fixture.
///
/// # Why this exists as a fence rather than as a habit
///
/// I have now found this gap twice by hand. First the rate STATES — the fixture
/// carried `priced` and nothing else, so a consumer pinning from it would never
/// meet `stated_zero` or `unpriced` and the first row carrying one would land on
/// a default arm. Then three whole fields: `plan.prices` (a tool I had shipped
/// that morning), `retired`, and `uncertain`.
///
/// Both were found by asking the same question by hand, and a third pass would
/// find a fourth gap later. This asks it on every run.
///
/// # What a miss costs
///
/// Consumers pin from these bytes -- ALF by my own recommendation.
///
/// MEASURED RATHER THAN ASSERTED, because the first version of this comment
/// said an absent field "can change and redden nothing", and that is false. The
/// three fields this fence was built after -- `retired`, `uncertain`,
/// `tier_vocabulary` -- are all asserted in `route.rs` by direct field access,
/// so a shape change would have reddened there.
///
/// What the fixture adds over those tests is a different guarantee, and it is
/// the one worth stating: a route test asserts the field a consumer ASKED FOR,
/// on a payload that test constructed. The fixture pins EVERY SERVED BYTE of a
/// real response, so it catches a change nobody thought to assert -- a renamed
/// neighbour, a dropped null, an added key. That is the class a targeted test
/// structurally cannot see, since it examines only what its author already had
/// in mind.
///
/// So the cost of a gap is narrower than I first wrote and still real: the
/// field keeps whatever coverage someone gave it deliberately, and loses the
/// coverage nobody had to think of.
///
/// # The three WRITE tools are exempt, and that is a finding rather than a gap
///
/// `catalog.correct`, `catalog.mark_artifact` and `catalog.retract_artifact`
/// have exactly one consumer: `ck-models`, in this repository. Their fields are
/// pinned where that consumer RENDERS them, in the CLI's own tests — checked
/// rather than assumed, and `restating_eras`, `had_live_mark` and `total_eras`
/// all appear there.
///
/// Adding them here would duplicate that coverage and make this fixture claim a
/// purpose it does not have: it pins what crosses the seam to OTHER repositories.
/// An operator tool whose only caller ships beside it does not cross one.
#[test]
fn every_read_response_field_reaches_the_fixture() {
    let src = include_str!("../../../fusiform-protocol/src/lib.rs");
    let golden: serde_json::Value = serde_json::from_str(GOLDEN).expect("the fixture parses");

    let mut present: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    collect_keys(&golden, &mut present);
    assert!(
        present.len() > 40,
        "the fixture must carry a substantial key set, or the absence checks \
         below pass because nothing was collected: got {}",
        present.len()
    );

    // Source-scanned rather than reflected, because Rust has no runtime field
    // list and a hand-written one is a second statement of the struct that can
    // drift from it. The same reasoning as the currency-policy fence next door.
    let (checked, missing) = missing_response_fields(
        src,
        &present,
        &[
            "CatalogGetResponse",
            "PlaneWire",
            "BillingRuleWire",
            "HistoryResponse",
            "StatusResponse",
            "PlanPricesResponse",
            "PlanPriceWire",
        ],
    );

    assert!(
        checked >= 40,
        "this examined {checked} fields across seven structs; fewer than 40 means \
         the scan broke rather than the protocol shrinking"
    );

    assert!(
        missing.is_empty(),
        "These served fields appear in no golden payload: {missing:?}. Add a case that produces the field."
    );
}

fn missing_response_fields(
    src: &str,
    present: &std::collections::BTreeSet<String>,
    structs: &[&str],
) -> (usize, Vec<String>) {
    let mut checked = 0usize;
    let mut missing = Vec::new();
    for want in structs {
        let start = src
            .find(&format!("pub struct {want} {{"))
            .unwrap_or_else(|| panic!("{want} must exist in the protocol crate"));
        let body = &src[start..];
        let end = body.find("\n}").expect("a struct body closes");
        for line in body[..end].lines() {
            let line = line.trim();
            let Some(rest) = line.strip_prefix("pub ") else {
                continue;
            };
            let Some(field) = rest.split(':').next() else {
                continue;
            };
            // `pub struct` itself and any method; fields end with a type.
            if field.contains(' ') || field.is_empty() {
                continue;
            }
            checked += 1;
            if !present.contains(field) {
                missing.push(format!("{want}.{field}"));
            }
        }
    }

    (checked, missing)
}

#[test]
fn planted_missing_response_field_is_reported() {
    let mut present = std::collections::BTreeSet::new();
    collect_keys(&serde_json::json!({"known": null}), &mut present);
    assert_eq!(
        missing_response_fields(
            "pub struct Response {\n pub known: String,\n pub lost: String,\n}",
            &present,
            &["Response"]
        )
        .1,
        ["Response.lost"]
    );
}

/// Every object key anywhere in a document.
fn collect_keys(value: &serde_json::Value, out: &mut std::collections::BTreeSet<String>) {
    match value {
        serde_json::Value::Object(map) => {
            for (k, v) in map {
                out.insert(k.clone());
                collect_keys(v, out);
            }
        }
        serde_json::Value::Array(items) => {
            for v in items {
                collect_keys(v, out);
            }
        }
        _ => {}
    }
}

/// Every fact key in `SERVED_FACTS` appears in the fixture.
///
/// # A different vocabulary from the response fields next door
///
/// The fence above checks the KEYS OF THE ENVELOPE — `models`, `withheld`,
/// `retired`. This checks the keys INSIDE it, which is a separate list with a
/// separate authority: `SERVED_FACTS` in the protocol crate, the table that
/// tells a consumer what fusiform can ever serve.
///
/// Asked separately because the first fence was green while this one was not:
/// `rate.reasoning` appeared in no case, and the envelope was complete.
///
/// # Why a rare key needs a case rather than incidental coverage
///
/// `rate.reasoning` is carried by 166 of 6,213 reasoning-capable models in the
/// live catalog, measured 2026-09-19. A consumer is unlikely to meet one by
/// accident and certain to meet one eventually, which is the worst combination:
/// the decoder path is cold until it is load-bearing.
///
/// It is also the key where getting the shape wrong costs most. 115 of those
/// rows restate the model's output rate and 29 publish a different number —
/// alibaba bills reasoning at 2.5x to 3.3x output, perplexity's sonar at 0.38x
/// — so a consumer that defaults the key to the output rate is wrong in BOTH
/// directions, and the errors partially cancel in aggregate while every row is
/// wrong.
#[test]
fn every_served_fact_key_reaches_the_fixture() {
    let src = include_str!("../../../fusiform-protocol/src/lib.rs");
    let golden: serde_json::Value = serde_json::from_str(GOLDEN).expect("the fixture parses");

    let mut present: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    collect_keys(&golden, &mut present);

    // Scanned from the table rather than listed here, so a key added to
    // `SERVED_FACTS` is checked without anyone remembering this test.
    //
    // SCOPED TO THE TABLE'S BODY, not to the whole file. My first version
    // matched every `key: "` in lib.rs and happened to collect exactly the 15
    // SERVED_FACTS entries — correct by accident rather than by construction,
    // since any other struct with a `key` field would have been swept in and
    // this fence would then demand a fixture example of something that is not a
    // served fact.
    //
    // The failure direction was safe (a loud, diagnosable red naming the key)
    // which is exactly why it would have survived: nothing would have gone
    // wrong until someone added an unrelated field, and the scan's SUBJECT
    // would have been wrong the whole time.
    let (count, missing) = missing_served_fact_keys(src, &present);
    assert!(
        count >= 15,
        "SERVED_FACTS carried 15 entries when this was written; found {count}, which \
         means the scan broke rather than the table shrinking"
    );
    assert!(
        missing.is_empty(),
        "served fact keys absent from the fixture: {missing:?}"
    );
}

fn missing_served_fact_keys(
    src: &str,
    present: &std::collections::BTreeSet<String>,
) -> (usize, Vec<String>) {
    let table = {
        let start = src
            .find("pub const SERVED_FACTS")
            .expect("the served-facts table must exist");
        let body = &src[start..];
        let end = body.find("\n];").expect("the table closes");
        &body[..end]
    };
    let keys: Vec<&str> = table
        .match_indices("key: \"")
        .filter_map(|(i, _)| {
            let rest = &table[i + 6..];
            rest.find('"').map(|end| &rest[..end])
        })
        .collect();

    let missing = keys
        .iter()
        .filter(|k| !present.contains(**k))
        .map(|k| (*k).to_string())
        .collect();
    (keys.len(), missing)
}

#[test]
fn planted_missing_served_fact_key_is_reported() {
    let mut present = std::collections::BTreeSet::new();
    collect_keys(&serde_json::json!({"known": 1}), &mut present);
    assert_eq!(missing_served_fact_keys("pub const SERVED_FACTS: &[Fact] = &[\n Fact { key: \"known\" },\n Fact { key: \"lost\" },\n];", &present).1, ["lost"]);
}
