//! The bytes a consumer actually receives, pinned.
//!
//! # Why this exists separately from the round-trip tests
//!
//! `fusiform-protocol` asserts that the served types round-trip through JSON.
//! That proves the types are self-consistent and proves nothing about what a
//! consumer sees: a field renamed on both sides round-trips perfectly and
//! breaks every consumer.
//!
//! SUBC's framing of the fleet's payload rule has two halves — DECLARATIONS
//! SHARED, OUTPUTS PRODUCER-PINNED. The shared declaration is the protocol
//! crate. This file is the other half: a golden fixture of an actual served
//! payload, so a schema change fails fusiform's build until the fixture moves
//! with it.
//!
//! # The fixture is minted by the producer, never written by hand
//!
//! This repository's rule, learned from a defect in a sibling crate: a
//! hand-written fixture encodes its author's understanding of the format, so
//! when the parser and the fixture come from one belief in one commit, a
//! non-vacuous test certifies the bug. The fixture below is regenerated by
//! running the real serve path over a real store — `UPDATE_GOLDEN=1 cargo test
//! -p fusiform-module --test golden_payload` — and reviewed as a diff.
//!
//! Reviewing the diff is the point. A regenerated fixture that nobody reads is
//! a rubber stamp; the value is that a schema change shows up as a concrete
//! before/after in the payload a consumer parses, at review time.

use cortexkit_store_types::{Isolation, StorageBackend, StorageDescriptor};
use fusiform_core::normalize::normalize_models_dev;
use fusiform_core::{
    BoundaryKind, Correction, FieldId, ObservationOutcome, SourceId, Timestamp, TokenClass,
};
use fusiform_module::route::serve_tool_call;
use fusiform_store::ingest::plan_ingest;
use fusiform_store::{CatalogStore, FactKey, NewEra, NewObservation};

const UPSTREAM: &str = include_str!("../../fusiform-core/fixtures/models-dev-excerpt.json");

/// A SYNTHETIC upstream document: one model publishing no `reasoning` key.
///
/// Inline rather than in the fixtures directory, deliberately. A file sitting
/// beside `models-dev-excerpt.json` would read as another real cut, and this is
/// not one — no model in today's live document omits the key. Keeping it here,
/// next to the reason, makes it impossible to mistake for measured data.
const UNKNOWN_REASONING: &str = r#"{
  "synthetic": {
    "id": "synthetic",
    "name": "Synthetic (not a real provider)",
    "models": {
      "unknown-reasoning": {
        "id": "unknown-reasoning",
        "name": "A model whose reasoning capability the upstream did not state",
        "limit": { "context": 128000, "output": 8192 }
      }
    }
  }
}"#;
/// A SYNTHETIC creator/reseller pair, so the fixture carries an INHERITED rate.
///
/// Without this the golden payload contains no `inherited_from` at all: the
/// marker is attached at serve time, and it needs a creator row publishing a
/// price for the same model id under a curated family. The real excerpt happens
/// to hold no such pair.
///
/// That absence matters because consumers PIN FROM THESE BYTES. ALF said so
/// explicitly, and a fixture that omits a served shape lets a wire change to it
/// land without reddening anything here — which is the entire job of a golden
/// payload.
///
/// `glm` -> `zai` is the real shipped mapping in model-creators.json, so this
/// exercises the actual table rather than a fixture that agrees with itself.
/// The creator is keyed `zai` because the lookup resolves on the PROVIDER KEY,
/// not the `id` field inside it — my first version keyed it
/// `synthetic-creator-zai` with `"id": "zai"` and produced no inheritance at
/// all, which is a fixture that would have passed while testing nothing. `zai`
/// is absent from the real excerpt (11 providers, checked), so there is no
/// collision to mask.
/// The reseller publishes NO rate at all, which is the population inheritance
/// serves after the stated_zero correction: a provider that publishes any rate
/// has a price card and is left alone.
const INHERITANCE_PAIR: &str = r#"{
  "zai": {
    "id": "zai",
    "name": "Synthetic zai entry (models are synthetic, the id is real)",
    "models": {
      "synthetic-glm": {
        "id": "synthetic-glm",
        "name": "A model whose weights the creator publishes and prices",
        "family": "glm",
        "open_weights": true,
        "limit": { "context": 128000, "output": 8192 },
        "cost": { "input": 0.075, "output": 0.25 }
      }
    }
  },
  "synthetic-reseller": {
    "id": "synthetic-reseller",
    "name": "Synthetic reseller publishing no price (not a real provider)",
    "models": {
      "synthetic-glm": {
        "id": "synthetic-glm",
        "name": "The same weights served by someone who publishes no rate",
        "family": "glm",
        "open_weights": true,
        "limit": { "context": 128000, "output": 8192 }
      }
    }
  }
}"#;
const GOLDEN: &str = include_str!("../fixtures/served-payloads.json");

/// The real upstream cut with the synthetic unknown-reasoning provider added.
///
/// Merged as JSON rather than concatenated as text, so a malformed splice fails
/// here instead of producing a document that parses into something unintended.
fn merged_upstream() -> String {
    let mut doc: serde_json::Value = serde_json::from_str(UPSTREAM).unwrap();
    let obj = doc.as_object_mut().expect("the upstream is an object");
    for src in [UNKNOWN_REASONING, INHERITANCE_PAIR] {
        let synthetic: serde_json::Value = serde_json::from_str(src).unwrap();
        for (k, v) in synthetic.as_object().expect("synthetic is an object") {
            assert!(
                obj.insert(k.clone(), v.clone()).is_none(),
                "a synthetic provider must not collide with a real one: {k}"
            );
        }
    }
    serde_json::to_string(&doc).unwrap()
}

/// A store whose contents are fixed, so the payload is reproducible.
///
/// Every instant IN THE STORE is a literal, so nothing about the data moves
/// between runs. One field in one payload still does: a read with no `at_ms`
/// resolves to now by definition, and its `resolved_at_ms` is a wall clock
/// reading. That case substitutes a placeholder — and the point-in-time case
/// below pins the same field exactly, so the field's spelling and type are
/// covered while its unpinnable value is not pretended to be fixed.
///
/// This is narrower than it first looked. The initial version of this file
/// claimed every instant was a literal, which was false for exactly that one
/// read, and the test failed on its second run.
fn store() -> (CatalogStore, tempfile::TempDir) {
    let dir = tempfile::tempdir().unwrap();
    let store = CatalogStore::open(&StorageDescriptor {
        module_id: "fusiform".to_string(),
        storage_namespace: "default".to_string(),
        isolation: Isolation::Module,
        backend: StorageBackend::Sqlite {
            path: dir.path().join("store.db").to_string_lossy().to_string(),
        },
    })
    .unwrap();

    // A seed, so the catalog exists.
    store
        .record_observation(&NewObservation {
            source: SourceId::ModelsDev,
            observed_at: Timestamp(1_000),
            outcome: ObservationOutcome::Seeded,
            normalized_hash: Some("seed-hash".into()),
            raw_hash: Some("seed-raw".into()),
            etag: None,
            duration_ms: Some(12),
            detail: None,
        })
        .unwrap();
    // ONE document, not two.
    //
    // A second `plan_ingest` at the same instant would diff the synthetic
    // document against the store and tombstone every model from the first --
    // ingest treats "absent from this document" as a withdrawal, which is
    // correct and is exactly why a fixture must present one document rather
    // than two. Caught by the schema's uniqueness constraint on first run.
    let catalog = normalize_models_dev(merged_upstream().as_bytes())
        .unwrap()
        .catalog;
    let plan = plan_ingest(&store, &catalog, Timestamp(1_000), BoundaryKind::Seed, None).unwrap();
    store.append_eras(&plan.eras).unwrap();

    // A model whose reasoning capability is UNKNOWN, from a document that is
    // deliberately synthetic and labelled as such.
    //
    // Every other row in this fixture comes from a real upstream cut, which is
    // this repository's rule: a hand-written fixture encodes its author's
    // understanding of the format. This one cannot, and the reason is worth
    // stating rather than hiding. Measured on the live document today: all
    // 6,291 models publish the `reasoning` key, so ABSENT does not occur
    // upstream and cannot be cut from it.
    //
    // It is pinned anyway because the null is the whole point of BROCA's
    // parser fix — `as_bool()` returns None on a JSON null, so absent, false
    // and null all collapse to false, and a capable model silently stops
    // reasoning. Their deny-drift test vendors THIS fixture, so without a null
    // row their check cannot cover the case it exists for.
    //
    // The alternative was to leave the wire shape unpinned until the upstream
    // produces one, which means the first real occurrence is also the first
    // test of the path.

    // A SECOND INGEST WITH ONE RATE WITHDRAWN, so the fixture carries an
    // `unpriced` rate produced by the ingest path rather than written by hand.
    //
    // `unpriced/missing_rate` is a TOMBSTONE: the upstream described the model
    // and stopped publishing a rate it used to publish. 153 eras in the live
    // catalog carry it today, so it is an ordinary served state rather than an
    // edge case — and the one a consumer most needs to get right, because a
    // withdrawn rate is emphatically NOT zero. A decoder that defaults it
    // charges nothing for a model that bills.
    //
    // Generated by `plan_ingest` rather than appended as a literal, for the
    // reason the inheritance case exists: a hand-written value pins what I
    // BELIEVE the producer emits, and the fixture's whole job is to pin what it
    // ACTUALLY emits. If `withdrawal_value` changes, this reddens; a literal
    // would not.
    let withdrawn = {
        let mut doc: serde_json::Value =
            serde_json::from_str(&merged_upstream()).expect("the merged upstream parses");
        let cost = doc["zhipuai"]["models"]["glm-4.5-flash"]["cost"]
            .as_object_mut()
            .expect("glm-4.5-flash has a cost object");
        assert!(
            cost.remove("cache_write").is_some(),
            "the key being withdrawn must exist first, or this ingest is a no-op \
             and the fixture silently loses the tombstone"
        );

        // A WHOLE MODEL withdrawn as well, so the fixture carries a RETIRED
        // row. The `retired` array was added for a consumer whose roster went
        // stale on an upstream rename, and it appeared nowhere in these bytes
        // — the field exists precisely so a named read of a retired model is
        // distinguishable from a read of an unknown one, and neither shape was
        // pinned.
        let models = doc["poe"]["models"]
            .as_object_mut()
            .expect("poe publishes models");
        assert!(
            models.remove("google/veo-3").is_some(),
            "the model being withdrawn must exist first, or the retirement is a \
             no-op and the case below reads an unknown model instead"
        );
        assert!(
            !models.is_empty(),
            "the provider must keep a model, or this withdraws the PROVIDER too \
             and the read refuses for a different reason than the one pinned"
        );
        serde_json::to_string(&doc).expect("the edited document serialises")
    };
    let obs = store
        .record_observation(&NewObservation {
            source: SourceId::ModelsDev,
            observed_at: Timestamp(1_500),
            outcome: ObservationOutcome::Changed { snapshot_seq: 2 },
            normalized_hash: Some("withdrawal-hash".into()),
            raw_hash: Some("withdrawal-raw".into()),
            etag: None,
            duration_ms: Some(210),
            detail: None,
        })
        .unwrap();
    let catalog = normalize_models_dev(withdrawn.as_bytes())
        .expect("the withdrawn document normalises")
        .catalog;
    let plan = plan_ingest(
        &store,
        &catalog,
        Timestamp(1_500),
        BoundaryKind::Observed,
        Some(obs),
    )
    .unwrap();
    assert!(
        plan.eras
            .iter()
            .any(|e| e.value_json.contains("missing_rate")),
        "the withdrawal must produce a tombstone, or the fixture pins nothing \
         new: got {} eras",
        plan.eras.len()
    );
    store.append_eras(&plan.eras).unwrap();

    // THE CURATED PLAN PRICES, applied exactly as boot applies them.
    //
    // Without this the whole `plan.prices` tool is absent from the fixture: I
    // shipped it and never pinned its wire shape, so a change to `prices`,
    // `unit_policy` or `tier_vocabulary` would redden nothing here. That is the
    // same gap the rate states had — a surface consumers pin from, covering
    // less than the wire carries.
    //
    // Applied through `store_rows(rows())` rather than hand-built, so the
    // fixture pins what the SHIPPED FILE produces. A synthetic row would pin a
    // shape nobody serves, and the curated file is the artifact under review.
    let plan_rows = fusiform_module::plan_prices::store_rows(fusiform_module::plan_prices::rows());
    assert!(
        !plan_rows.is_empty(),
        "the curated file must yield rows, or the plan.prices cases below pin an \
         empty answer and prove nothing"
    );
    store.append_plan_prices(&plan_rows).unwrap();

    // A failed poll, so the status payload carries a failure class. An
    // all-successful history would leave the fields a consumer reads during an
    // incident unpinned.
    store
        .record_observation(&NewObservation {
            source: SourceId::ModelsDev,
            observed_at: Timestamp(2_000),
            outcome: ObservationOutcome::Failed {
                class: fusiform_core::FailureClass::HttpStatus,
            },
            normalized_hash: None,
            raw_hash: None,
            etag: None,
            duration_ms: Some(87),
            detail: Some("upstream returned 503".into()),
        })
        .unwrap();

    // A correction, so the withheld list and the correction extent are pinned.
    // These are the fields a consumer needs exactly when something is wrong,
    // which is when nobody is regenerating fixtures.
    store
        .append_eras(&[NewEra {
            source: SourceId::ModelsDev,
            provider_id: "anthropic".into(),
            model_id: "claude-sonnet-4-5".into(),
            fact_key: FactKey::rate(TokenClass::Input),
            value_json: r#"{"state":"priced","currency":"USD","exponent":9,"units":3000000000}"#
                .into(),
            boundary_at: Timestamp(9_000),
            boundary_kind: BoundaryKind::Corrected(Correction {
                fields: vec![FieldId::Rate {
                    class: TokenClass::Input,
                }],
                affected_from: Timestamp(3_000),
                affected_until: Timestamp(9_000),
                reason: "normalizer scaled tiered rates by 1000x".to_string(),
            }),
            observation_id: None,
        }])
        .unwrap();

    (store, dir)
}

/// The calls whose payloads are pinned, each with why it is here.
fn cases() -> Vec<(&'static str, String)> {
    vec![
        (
            "catalog.get — one model, current",
            r#"{"name":"catalog.get","arguments":{"provider_id":"anthropic","model_id":"claude-sonnet-4-5"}}"#.to_string(),
        ),
        (
            // Inside the corrected interval: exercises the withheld list, which
            // is the shape a consumer sees when fusiform refuses a fact.
            "catalog.get — inside a corrected interval",
            r#"{"name":"catalog.get","arguments":{"provider_id":"anthropic","model_id":"claude-sonnet-4-5","at_ms":5000}}"#.to_string(),
        ),
        (
            // A PUBLISHED ZERO, which is a price rather than an absence: the
            // provider states this dimension is free. Distinct on the wire from
            // `unpriced` below, and collapsing them is the defect this
            // vocabulary exists to prevent — one means "costs nothing", the
            // other means "nobody said".
            //
            // Pinned because consumers pin from these bytes. Until now the
            // fixture carried only `priced`, so a consumer building a decoder
            // against it would never meet this state, and the first row that
            // carried it would land on a default arm.
            "catalog.get — a rate published as zero",
            r#"{"name":"catalog.get","arguments":{"provider_id":"greenpt","model_id":"green-s","fact_prefixes":["rate."]}}"#.to_string(),
        ),
        (
            // NO COST OBJECT UPSTREAM, so every rate is `unpriced` with a
            // reason. The reason is load-bearing: a consumer that treats this
            // as zero charges nothing for a model that may bill, and one that
            // treats it as an error refuses a model that is merely undocumented.
            //
            // The other half of the pair above. Both states now appear in the
            // fixture, so a decoder pinned to these bytes has to handle all
            // three of `priced`, `stated_zero` and `unpriced`.
            "catalog.get — a model the upstream prices not at all",
            r#"{"name":"catalog.get","arguments":{"provider_id":"anyapi","model_id":"anthropic/claude-opus-4-6"}}"#.to_string(),
        ),
        (
            // The WITHDRAWN rate, tombstoned as `unpriced/missing_rate` by the
            // second ingest above. Completes the rate vocabulary in this
            // fixture: `priced`, `stated_zero`, `unpriced`, and `inherited_from`
            // all appear in bytes a consumer can pin.
            "catalog.get — a rate the upstream withdrew",
            r#"{"name":"catalog.get","arguments":{"provider_id":"zhipuai","model_id":"glm-4.5-flash","fact_prefixes":["rate."]}}"#.to_string(),
        ),
        (
            // The whole `plan.prices` surface: priced tiers, a REFUSAL row, the
            // unit policy and the tier vocabulary. Every one of these was
            // unpinned until now.
            //
            // The refusal matters most — `openai/pro` carries no price because
            // the API plan string does not resolve to a vendor tier, and a
            // consumer that reads a missing price as free bills nothing for a
            // subscription that costs money.
            "plan.prices — every curated row",
            r#"{"name":"plan.prices","arguments":{}}"#.to_string(),
        ),
        (
            // A NAMED READ OF A RETIRED MODEL. The model is gone from the
            // upstream, so `models` is empty and `retired` names it with the
            // instant it went.
            //
            // Distinct from a read of an UNKNOWN model, which refuses with
            // no_coverage. Collapsing the two is what sent a consumer hunting a
            // deletion when the upstream had renamed a provider, and this is
            // the shape that tells them apart.
            "catalog.get — a named read of a retired model",
            r#"{"name":"catalog.get","arguments":{"provider_id":"poe","model_id":"google/veo-3"}}"#.to_string(),
        ),
        (
            // A READ INSIDE AN UNOBSERVED WINDOW, which populates `uncertain`.
            //
            // The withdrawal landed at t=1500 and the observation before it was
            // t=1000, so at t=1200 the store knows the value it served and does
            // NOT know whether it still held — the change could have happened
            // either side of the instant asked for.
            //
            // Unpinned until now, and it is the field a consumer needs to
            // reconstruct a past decision honestly: flattening the bracket to a
            // point value turns "nobody was watching" into a confident answer.
            "catalog.get — an instant inside an unobserved window",
            r#"{"name":"catalog.get","arguments":{"provider_id":"zhipuai","model_id":"glm-4.5-flash","at_ms":1200,"fact_prefixes":["rate."]}}"#.to_string(),
        ),
        (
            // `rate.reasoning`, the one served fact key absent from every other
            // case here — found by asking the fact-key question the response
            // field fence does not cover.
            //
            // Worth its own case rather than incidental coverage: only 166 of
            // 6,213 reasoning-capable models in the live catalog carry this key,
            // so a consumer is unlikely to meet one by accident and very likely
            // to meet one eventually. 115 of those restate the model's output
            // rate, and 29 publish a genuinely different number — alibaba bills
            // reasoning at 2.5x to 3.3x output, perplexity's sonar at 0.38x — so
            // a decoder that defaults this key to the output rate is wrong in
            // BOTH directions and the errors cancel in aggregate.
            "catalog.get — a model that prices reasoning separately",
            r#"{"name":"catalog.get","arguments":{"provider_id":"nebius","model_id":"Qwen/Qwen3-Next-80B-A3B-Thinking","fact_prefixes":["rate."]}}"#.to_string(),
        ),
        (
            "catalog.history — a corrected fact",
            r#"{"name":"catalog.history","arguments":{"provider_id":"anthropic","model_id":"claude-sonnet-4-5","fact_key":"rate.input"}}"#.to_string(),
        ),
        (
            // The wire shape of an UNKNOWN capability, which is the case
            // BROCA's parser fix is entirely about. Pinned here because the
            // null was proven at the core boundary and never proven to survive
            // to the wire -- correct at one layer, unverified at the next.
            "catalog.get — a model whose reasoning capability is unknown",
            r#"{"name":"catalog.get","arguments":{"provider_id":"synthetic","model_id":"unknown-reasoning"}}"#.to_string(),
        ),
        (
            // An INHERITED rate, a shape absent everywhere else in this fixture.
            // The reseller publishes no rate of its own, so every rate on this
            // row is borrowed from the creator and carries `inherited_from`.
            //
            // Pinned because consumers pin from these bytes: with no case
            // requesting this row, the marker never appears in the golden
            // payload and a wire change to it lands without reddening anything.
            // Astrocyte's inherited-rate test was SEEDED FROM this case
            // (astrocyte aba2219): they copied the marked row's bytes into a
            // literal, so the case is an origin rather than a dependency.
            // Renaming or rearranging it does not break them — their test holds
            // its own copy and asserts about the WIRE SHAPE, not about any row
            // in this store.
            //
            // The note exists so a future reader knows where those bytes came
            // from, which is a question that has no answer from their side. My
            // first version of this comment said "pins byte-for-byte" and
            // warned that an edit here breaks a test there; ASTRO corrected it.
            // An overstated coupling is its own defect — it makes a reader
            // afraid of an edit that is actually safe, and a warning nobody can
            // verify is indistinguishable from one that is wrong.
            "inherited rate",
            r#"{"name":"catalog.get","arguments":{"provider_id":"synthetic-reseller","model_id":"synthetic-glm"}}"#.to_string(),
        ),
        (
            // The creator's own row, as the CONTROL: it publishes its own price
            // and must carry no marker. Without this arm the fixture cannot
            // tell "inheritance works" from "everything is marked inherited".
            "creator row, unmarked",
            r#"{"name":"catalog.get","arguments":{"provider_id":"zai","model_id":"synthetic-glm"}}"#.to_string(),
        ),
        (
            "catalog.status",
            r#"{"name":"catalog.status","arguments":{"polls":3}}"#.to_string(),
        ),
    ]
}

/// The one field that cannot be pinned, and what stands in for it.
const NOW_PLACEHOLDER: i64 = -1;

fn render() -> String {
    let (store, _dir) = store();
    let mut doc = serde_json::Map::new();
    for (label, body) in cases() {
        let response = serve_tool_call(&store, body.as_bytes())
            .unwrap_or_else(|e| panic!("{label} must serve: {e:?}"));
        let mut value = serde_json::to_value(&response).unwrap();

        // A read with no `at_ms` resolves to wall-clock now. Substituted rather
        // than dropped: the KEY stays in the fixture, so a rename or a type
        // change still shows up as a diff, and only the unpinnable number is
        // replaced. Asserted separately below that the real value is sane.
        if !body.contains("at_ms") {
            if let Some(resolved) = value.get_mut("resolved_at_ms") {
                *resolved = serde_json::json!(NOW_PLACEHOLDER);
            }
        }

        doc.insert(
            label.to_string(),
            serde_json::json!({
                "request": serde_json::from_str::<serde_json::Value>(&body).unwrap(),
                "response": value,
            }),
        );
    }
    let mut text = serde_json::to_string_pretty(&serde_json::Value::Object(doc)).unwrap();
    text.push('\n');
    text
}

/// The substituted field really does carry a current instant.
///
/// The placeholder above keeps the fixture stable, and on its own it would let
/// `resolved_at_ms` become anything at all — zero, a constant, last week —
/// without any test noticing. This checks the real value.
#[test]
fn a_current_read_resolves_to_an_instant_near_now() {
    let (store, _dir) = store();
    let before = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_millis() as i64;

    let response = serve_tool_call(
        &store,
        br#"{"name":"catalog.get","arguments":{"provider_id":"anthropic","model_id":"claude-sonnet-4-5"}}"#,
    )
    .unwrap();
    let value = serde_json::to_value(&response).unwrap();
    let resolved = value
        .get("resolved_at_ms")
        .and_then(|v| v.as_i64())
        .expect("a current read reports the instant it resolved to");

    let after = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_millis() as i64;

    assert!(
        resolved >= before && resolved <= after,
        "a current read must resolve to now: got {resolved}, expected between \
         {before} and {after}"
    );
}

/// The served payloads have not changed.
#[test]
fn the_served_payloads_match_the_golden_fixture() {
    let rendered = render();

    if std::env::var("UPDATE_GOLDEN").is_ok() {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/fixtures/served-payloads.json");
        std::fs::write(path, &rendered).unwrap();
        eprintln!("golden fixture regenerated at {path} — review the diff");
        return;
    }

    if rendered != GOLDEN {
        // The diff rather than the whole document: a 200-line dump of two
        // similar payloads is unreadable, and the changed lines are the point.
        let mut differing = Vec::new();
        for (i, (a, b)) in GOLDEN.lines().zip(rendered.lines()).enumerate() {
            if a != b {
                differing.push(format!("  line {}:\n    was: {a}\n    now: {b}", i + 1));
            }
        }
        if GOLDEN.lines().count() != rendered.lines().count() {
            differing.push(format!(
                "  line count: was {}, now {}",
                GOLDEN.lines().count(),
                rendered.lines().count()
            ));
        }
        panic!(
            "the served payload changed. A consumer parses these bytes.\n\n{}\n\n\
             If the change is intended, regenerate with:\n  \
             UPDATE_GOLDEN=1 cargo test -p fusiform-module --test golden_payload\n\
             and bump fusiform-protocol's version — CI enforces that separately.",
            differing.join("\n")
        );
    }
}

/// The fixture is not empty, and carries the shapes it exists to pin.
///
/// A golden test whose fixture lost its interesting cases still passes, because
/// it compares the file to itself. This asserts the file contains the shapes
/// that motivated it — so a regeneration that silently dropped the correction
/// path fails here rather than passing quietly.
#[test]
fn the_fixture_pins_the_shapes_it_exists_for() {
    for needle in [
        // A priced rate with its explicit exponent and currency.
        r#""state": "priced""#,
        r#""exponent": 9"#,
        r#""currency": "USD""#,
        // The withheld list and a correction's extent and reason.
        r#""withheld""#,
        r#""affected_from_ms""#,
        "normalizer scaled tiered rates by 1000x",
        // A failure class on a recorded poll.
        r#""failure_class": "http_status""#,
        r#""outcome": "failed""#,
        // An observation window on an era.
        r#""boundary_kind""#,
        // The placeholder for the one unpinnable field. If this vanishes, the
        // substitution stopped happening and the fixture will churn.
        r#""resolved_at_ms": -1"#,
    ] {
        assert!(
            GOLDEN.contains(needle),
            "the golden fixture no longer pins {needle:?} — a regeneration \
             dropped a case this file exists to hold"
        );
    }
}

/// Every field of every READ response appears somewhere in the fixture.
///
/// # Why this exists as a fence rather than as a habit
///
/// I have now found this gap twice by hand. First the rate STATES — the fixture
/// carried `priced` and nothing else, so a consumer pinning from it would never
/// meet `stated_zero` or `unpriced` and the first row carrying one would land on
/// a default arm. Then three whole fields: `plan.prices` (a tool I had shipped
/// that morning), `retired`, and `uncertain`.
///
/// Both were found by asking the same question by hand, and a third pass would
/// find a fourth gap later. This asks it on every run.
///
/// # What a miss costs
///
/// Consumers pin from these bytes — ALF by my own recommendation. A field absent
/// from the fixture is a field whose wire shape no test here constrains, so it
/// can change and redden nothing until a consumer's decoder meets it in
/// production. That is quieter than a build failure and lands further from the
/// change.
///
/// # The three WRITE tools are exempt, and that is a finding rather than a gap
///
/// `catalog.correct`, `catalog.mark_artifact` and `catalog.retract_artifact`
/// have exactly one consumer: `ck-models`, in this repository. Their fields are
/// pinned where that consumer RENDERS them, in the CLI's own tests — checked
/// rather than assumed, and `restating_eras`, `had_live_mark` and `total_eras`
/// all appear there.
///
/// Adding them here would duplicate that coverage and make this fixture claim a
/// purpose it does not have: it pins what crosses the seam to OTHER repositories.
/// An operator tool whose only caller ships beside it does not cross one.
#[test]
fn every_read_response_field_reaches_the_fixture() {
    let src = include_str!("../../fusiform-protocol/src/lib.rs");
    let golden: serde_json::Value = serde_json::from_str(GOLDEN).expect("the fixture parses");

    let mut present: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    collect_keys(&golden, &mut present);
    assert!(
        present.len() > 40,
        "the fixture must carry a substantial key set, or the absence checks \
         below pass because nothing was collected: got {}",
        present.len()
    );

    // Source-scanned rather than reflected, because Rust has no runtime field
    // list and a hand-written one is a second statement of the struct that can
    // drift from it. The same reasoning as the currency-policy fence next door.
    let mut checked = 0usize;
    let mut missing: Vec<String> = Vec::new();
    for want in [
        "CatalogGetResponse",
        "HistoryResponse",
        "StatusResponse",
        "PlanPricesResponse",
    ] {
        let start = src
            .find(&format!("pub struct {want} {{"))
            .unwrap_or_else(|| panic!("{want} must exist in the protocol crate"));
        let body = &src[start..];
        let end = body.find("\n}").expect("a struct body closes");
        for line in body[..end].lines() {
            let line = line.trim();
            let Some(rest) = line.strip_prefix("pub ") else {
                continue;
            };
            let Some(field) = rest.split(':').next() else {
                continue;
            };
            // `pub struct` itself and any method; fields end with a type.
            if field.contains(' ') || field.is_empty() {
                continue;
            }
            checked += 1;
            if !present.contains(field) {
                missing.push(format!("{want}.{field}"));
            }
        }
    }

    assert!(
        checked >= 25,
        "this examined {checked} fields across four structs; they carried 29 \
         when this was written, so a collapse means the scan broke rather than \
         the protocol shrinking"
    );

    assert!(
        missing.is_empty(),
        "\n\nThese served fields appear in no golden payload:\n\n  {}\n\n\
         Consumers pin from this fixture, so a field absent here has its wire \
         shape constrained by nothing: it can change and redden no test until a \
         consumer's decoder meets it in production.\n\n\
         Add a case to `cases()` that PRODUCES the field rather than a synthetic \
         payload carrying it — the fixture's value is that it records what the \
         serve path actually emits.\n",
        missing.join("\n  ")
    );
}

/// Every object key anywhere in a document.
fn collect_keys(value: &serde_json::Value, out: &mut std::collections::BTreeSet<String>) {
    match value {
        serde_json::Value::Object(map) => {
            for (k, v) in map {
                out.insert(k.clone());
                collect_keys(v, out);
            }
        }
        serde_json::Value::Array(items) => {
            for v in items {
                collect_keys(v, out);
            }
        }
        _ => {}
    }
}

/// Every fact key in `SERVED_FACTS` appears in the fixture.
///
/// # A different vocabulary from the response fields next door
///
/// The fence above checks the KEYS OF THE ENVELOPE — `models`, `withheld`,
/// `retired`. This checks the keys INSIDE it, which is a separate list with a
/// separate authority: `SERVED_FACTS` in the protocol crate, the table that
/// tells a consumer what fusiform can ever serve.
///
/// Asked separately because the first fence was green while this one was not:
/// `rate.reasoning` appeared in no case, and the envelope was complete.
///
/// # Why a rare key needs a case rather than incidental coverage
///
/// `rate.reasoning` is carried by 166 of 6,213 reasoning-capable models in the
/// live catalog, measured 2026-09-19. A consumer is unlikely to meet one by
/// accident and certain to meet one eventually, which is the worst combination:
/// the decoder path is cold until it is load-bearing.
///
/// It is also the key where getting the shape wrong costs most. 115 of those
/// rows restate the model's output rate and 29 publish a different number —
/// alibaba bills reasoning at 2.5x to 3.3x output, perplexity's sonar at 0.38x
/// — so a consumer that defaults the key to the output rate is wrong in BOTH
/// directions, and the errors partially cancel in aggregate while every row is
/// wrong.
#[test]
fn every_served_fact_key_reaches_the_fixture() {
    let src = include_str!("../../fusiform-protocol/src/lib.rs");
    let golden: serde_json::Value = serde_json::from_str(GOLDEN).expect("the fixture parses");

    let mut present: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    collect_keys(&golden, &mut present);

    // Scanned from the table rather than listed here, so a key added to
    // `SERVED_FACTS` is checked without anyone remembering this test.
    let keys: Vec<&str> = src
        .match_indices("key: \"")
        .filter_map(|(i, _)| {
            let rest = &src[i + 6..];
            rest.find('"').map(|end| &rest[..end])
        })
        .collect();

    assert!(
        keys.len() >= 15,
        "SERVED_FACTS carried 15 entries when this was written; found {}, which \
         means the scan broke rather than the table shrinking",
        keys.len()
    );

    let missing: Vec<&&str> = keys.iter().filter(|k| !present.contains(**k)).collect();
    assert!(
        missing.is_empty(),
        "\n\nThese served fact keys appear in no golden payload:\n\n  {:?}\n\n\
         A consumer pinning from this fixture never meets them, so their wire \
         shape is constrained by nothing here.\n\n\
         Add a case reading a model that PUBLISHES the key. If the excerpt has \
         no such model, that is the finding — the fixture's upstream cut does \
         not cover a fact fusiform serves.\n",
        missing
    );
}
