//! The bytes a consumer actually receives, pinned.
//!
//! # Why this exists separately from the round-trip tests
//!
//! `fusiform-protocol` asserts that the served types round-trip through JSON.
//! That proves the types are self-consistent and proves nothing about what a
//! consumer sees: a field renamed on both sides round-trips perfectly and
//! breaks every consumer.
//!
//! SUBC's framing of the fleet's payload rule has two halves — DECLARATIONS
//! SHARED, OUTPUTS PRODUCER-PINNED. The shared declaration is the protocol
//! crate. This file is the other half: a golden fixture of an actual served
//! payload, so a schema change fails fusiform's build until the fixture moves
//! with it.
//!
//! # The fixture is minted by the producer, never written by hand
//!
//! This repository's rule, learned from a defect in a sibling crate: a
//! hand-written fixture encodes its author's understanding of the format, so
//! when the parser and the fixture come from one belief in one commit, a
//! non-vacuous test certifies the bug. The fixture below is regenerated by
//! running the real serve path over a real store — `UPDATE_GOLDEN=1 cargo test
//! -p fusiform-module --test golden_payload` — and reviewed as a diff.
//!
//! Reviewing the diff is the point. A regenerated fixture that nobody reads is
//! a rubber stamp; the value is that a schema change shows up as a concrete
//! before/after in the payload a consumer parses, at review time.

use cortexkit_store_types::{Isolation, StorageBackend, StorageDescriptor};
use fusiform_core::normalize::normalize_models_dev;
use fusiform_core::{
    BoundaryKind, Correction, FieldId, ObservationOutcome, SourceId, Timestamp, TokenClass,
};
use fusiform_module::route::serve_tool_call;
use fusiform_store::ingest::plan_ingest;
use fusiform_store::{CatalogStore, FactKey, NewEra, NewObservation};

const UPSTREAM: &str = include_str!("../../fusiform-core/fixtures/models-dev-excerpt.json");
const GOLDEN: &str = include_str!("../fixtures/served-payloads.json");

/// A store whose contents are fixed, so the payload is reproducible.
///
/// Every instant IN THE STORE is a literal, so nothing about the data moves
/// between runs. One field in one payload still does: a read with no `at_ms`
/// resolves to now by definition, and its `resolved_at_ms` is a wall clock
/// reading. That case substitutes a placeholder — and the point-in-time case
/// below pins the same field exactly, so the field's spelling and type are
/// covered while its unpinnable value is not pretended to be fixed.
///
/// This is narrower than it first looked. The initial version of this file
/// claimed every instant was a literal, which was false for exactly that one
/// read, and the test failed on its second run.
fn store() -> (CatalogStore, tempfile::TempDir) {
    let dir = tempfile::tempdir().unwrap();
    let store = CatalogStore::open(&StorageDescriptor {
        module_id: "fusiform".to_string(),
        storage_namespace: "default".to_string(),
        isolation: Isolation::Module,
        backend: StorageBackend::Sqlite {
            path: dir.path().join("store.db").to_string_lossy().to_string(),
        },
    })
    .unwrap();

    // A seed, so the catalog exists.
    store
        .record_observation(&NewObservation {
            source: SourceId::ModelsDev,
            observed_at: Timestamp(1_000),
            outcome: ObservationOutcome::Seeded,
            normalized_hash: Some("seed-hash".into()),
            raw_hash: Some("seed-raw".into()),
            etag: None,
            duration_ms: Some(12),
            detail: None,
        })
        .unwrap();
    let catalog = normalize_models_dev(UPSTREAM.as_bytes()).unwrap().catalog;
    let plan = plan_ingest(&store, &catalog, Timestamp(1_000), BoundaryKind::Seed, None).unwrap();
    store.append_eras(&plan.eras).unwrap();

    // A failed poll, so the status payload carries a failure class. An
    // all-successful history would leave the fields a consumer reads during an
    // incident unpinned.
    store
        .record_observation(&NewObservation {
            source: SourceId::ModelsDev,
            observed_at: Timestamp(2_000),
            outcome: ObservationOutcome::Failed {
                class: fusiform_core::FailureClass::HttpStatus,
            },
            normalized_hash: None,
            raw_hash: None,
            etag: None,
            duration_ms: Some(87),
            detail: Some("upstream returned 503".into()),
        })
        .unwrap();

    // A correction, so the withheld list and the correction extent are pinned.
    // These are the fields a consumer needs exactly when something is wrong,
    // which is when nobody is regenerating fixtures.
    store
        .append_eras(&[NewEra {
            source: SourceId::ModelsDev,
            provider_id: "anthropic".into(),
            model_id: "claude-sonnet-4-5".into(),
            fact_key: FactKey::rate(TokenClass::Input),
            value_json: r#"{"state":"priced","currency":"USD","exponent":9,"units":3000000000}"#
                .into(),
            boundary_at: Timestamp(9_000),
            boundary_kind: BoundaryKind::Corrected(Correction {
                fields: vec![FieldId::Rate {
                    class: TokenClass::Input,
                }],
                affected_from: Timestamp(3_000),
                affected_until: Timestamp(9_000),
                reason: "normalizer scaled tiered rates by 1000x".to_string(),
            }),
            observation_id: None,
        }])
        .unwrap();

    (store, dir)
}

/// The calls whose payloads are pinned, each with why it is here.
fn cases() -> Vec<(&'static str, String)> {
    vec![
        (
            "catalog.get — one model, current",
            r#"{"name":"catalog.get","arguments":{"provider_id":"anthropic","model_id":"claude-sonnet-4-5"}}"#.to_string(),
        ),
        (
            // Inside the corrected interval: exercises the withheld list, which
            // is the shape a consumer sees when fusiform refuses a fact.
            "catalog.get — inside a corrected interval",
            r#"{"name":"catalog.get","arguments":{"provider_id":"anthropic","model_id":"claude-sonnet-4-5","at_ms":5000}}"#.to_string(),
        ),
        (
            "catalog.history — a corrected fact",
            r#"{"name":"catalog.history","arguments":{"provider_id":"anthropic","model_id":"claude-sonnet-4-5","fact_key":"rate.input"}}"#.to_string(),
        ),
        (
            "catalog.status",
            r#"{"name":"catalog.status","arguments":{"polls":3}}"#.to_string(),
        ),
    ]
}

/// The one field that cannot be pinned, and what stands in for it.
const NOW_PLACEHOLDER: i64 = -1;

fn render() -> String {
    let (store, _dir) = store();
    let mut doc = serde_json::Map::new();
    for (label, body) in cases() {
        let response = serve_tool_call(&store, body.as_bytes())
            .unwrap_or_else(|e| panic!("{label} must serve: {e:?}"));
        let mut value = serde_json::to_value(&response).unwrap();

        // A read with no `at_ms` resolves to wall-clock now. Substituted rather
        // than dropped: the KEY stays in the fixture, so a rename or a type
        // change still shows up as a diff, and only the unpinnable number is
        // replaced. Asserted separately below that the real value is sane.
        if !body.contains("at_ms") {
            if let Some(resolved) = value.get_mut("resolved_at_ms") {
                *resolved = serde_json::json!(NOW_PLACEHOLDER);
            }
        }

        doc.insert(
            label.to_string(),
            serde_json::json!({
                "request": serde_json::from_str::<serde_json::Value>(&body).unwrap(),
                "response": value,
            }),
        );
    }
    let mut text = serde_json::to_string_pretty(&serde_json::Value::Object(doc)).unwrap();
    text.push('\n');
    text
}

/// The substituted field really does carry a current instant.
///
/// The placeholder above keeps the fixture stable, and on its own it would let
/// `resolved_at_ms` become anything at all — zero, a constant, last week —
/// without any test noticing. This checks the real value.
#[test]
fn a_current_read_resolves_to_an_instant_near_now() {
    let (store, _dir) = store();
    let before = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_millis() as i64;

    let response = serve_tool_call(
        &store,
        br#"{"name":"catalog.get","arguments":{"provider_id":"anthropic","model_id":"claude-sonnet-4-5"}}"#,
    )
    .unwrap();
    let value = serde_json::to_value(&response).unwrap();
    let resolved = value
        .get("resolved_at_ms")
        .and_then(|v| v.as_i64())
        .expect("a current read reports the instant it resolved to");

    let after = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_millis() as i64;

    assert!(
        resolved >= before && resolved <= after,
        "a current read must resolve to now: got {resolved}, expected between \
         {before} and {after}"
    );
}

/// The served payloads have not changed.
#[test]
fn the_served_payloads_match_the_golden_fixture() {
    let rendered = render();

    if std::env::var("UPDATE_GOLDEN").is_ok() {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/fixtures/served-payloads.json");
        std::fs::write(path, &rendered).unwrap();
        eprintln!("golden fixture regenerated at {path} — review the diff");
        return;
    }

    if rendered != GOLDEN {
        // The diff rather than the whole document: a 200-line dump of two
        // similar payloads is unreadable, and the changed lines are the point.
        let mut differing = Vec::new();
        for (i, (a, b)) in GOLDEN.lines().zip(rendered.lines()).enumerate() {
            if a != b {
                differing.push(format!("  line {}:\n    was: {a}\n    now: {b}", i + 1));
            }
        }
        if GOLDEN.lines().count() != rendered.lines().count() {
            differing.push(format!(
                "  line count: was {}, now {}",
                GOLDEN.lines().count(),
                rendered.lines().count()
            ));
        }
        panic!(
            "the served payload changed. A consumer parses these bytes.\n\n{}\n\n\
             If the change is intended, regenerate with:\n  \
             UPDATE_GOLDEN=1 cargo test -p fusiform-module --test golden_payload\n\
             and bump fusiform-protocol's version — CI enforces that separately.",
            differing.join("\n")
        );
    }
}

/// The fixture is not empty, and carries the shapes it exists to pin.
///
/// A golden test whose fixture lost its interesting cases still passes, because
/// it compares the file to itself. This asserts the file contains the shapes
/// that motivated it — so a regeneration that silently dropped the correction
/// path fails here rather than passing quietly.
#[test]
fn the_fixture_pins_the_shapes_it_exists_for() {
    for needle in [
        // A priced rate with its explicit exponent and currency.
        r#""state": "priced""#,
        r#""exponent": 9"#,
        r#""currency": "USD""#,
        // The withheld list and a correction's extent and reason.
        r#""withheld""#,
        r#""affected_from_ms""#,
        "normalizer scaled tiered rates by 1000x",
        // A failure class on a recorded poll.
        r#""failure_class": "http_status""#,
        r#""outcome": "failed""#,
        // An observation window on an era.
        r#""boundary_kind""#,
        // The placeholder for the one unpinnable field. If this vanishes, the
        // substitution stopped happening and the fixture will churn.
        r#""resolved_at_ms": -1"#,
    ] {
        assert!(
            GOLDEN.contains(needle),
            "the golden fixture no longer pins {needle:?} — a regeneration \
             dropped a case this file exists to hold"
        );
    }
}
