//! The protocol types decode the bytes this server actually serves.
//!
//! # Why this exists
//!
//! `RateValue` moved into `fusiform-protocol` so consumers could stop writing
//! their own decoders — and it did not describe the wire. ASTRO found it by
//! building against the crate: `missing field "amount"` on every priced rate,
//! because the type nested an `Amount` and the server serves those fields flat.
//!
//! The type was a DOMAIN type promoted to a wire type without anyone checking
//! that it described the wire, and nothing in this repository could notice. The
//! server never serializes through it: `json_rate` in fusiform-store hand-writes
//! the stored string and the serve path passes those bytes through. Two paths
//! answering "what is a rate on the wire", and no test compared them.
//!
//! The golden fixture could not catch it either, and that is the part worth
//! stating: it is generated BY the serve path, so it faithfully recorded bytes
//! the protocol type could not decode. Byte-identical across the move meant the
//! WIRE had not changed. It said nothing about whether the type matched.
//!
//! So this fence is the missing comparison: take the fixture the producer
//! generates, and decode it with the types a consumer compiles against.

use fusiform_protocol::money::{Floor, RateValue};

const SERVED: &str = include_str!("../fixtures/served-payloads.json");

/// Every priced rate in the served fixture decodes with the protocol type.
///
/// Driven from the FIXTURE rather than a literal, so a change to what the
/// server serves reaches this test without anyone remembering to update it —
/// which is the property the hand-copied literal in the original probe lacked.
#[test]
fn every_served_rate_decodes_with_the_protocol_type() {
    let doc: serde_json::Value = serde_json::from_str(SERVED).expect("the fixture parses");

    let mut rates = Vec::new();
    collect_priced(&doc, &mut rates);

    // NON-VACUITY: a fixture with no priced rates would pass the loop below
    // while proving nothing, which is the shape that let the original defect
    // through in the first place.
    assert!(
        !rates.is_empty(),
        "the fixture must contain priced rates, or this fence asserts nothing"
    );

    for raw in &rates {
        let decoded: Result<RateValue, _> = serde_json::from_value((*raw).clone());
        let value = decoded.unwrap_or_else(|e| {
            panic!(
                "the protocol type must decode what this server serves, and did \
                 not: {e}\n  served: {raw}\n\nA consumer compiling against \
                 fusiform-protocol reads exactly these bytes. If the type and \
                 the wire disagree, the crate that exists to remove hand-written \
                 decoders cannot replace one."
            )
        });

        match value {
            RateValue::Priced { amount, floor } => {
                assert!(
                    amount.units > 0,
                    "a priced rate must carry its units through the decode: {raw}"
                );
                // Absent from the wire today, so it must arrive as the state
                // that says nobody established it — never as no-minimum.
                assert_eq!(
                    floor,
                    Floor::Unknown,
                    "a rate served without a floor must decode as Unknown, not \
                     as an established absence: {raw}"
                );
            }
            other => panic!("a priced rate must decode as Priced, got {other:?}"),
        }
    }
}

fn collect_priced<'a>(node: &'a serde_json::Value, out: &mut Vec<&'a serde_json::Value>) {
    match node {
        serde_json::Value::Object(map) => {
            if map.get("state").and_then(|s| s.as_str()) == Some("priced") {
                out.push(node);
            }
            for v in map.values() {
                collect_priced(v, out);
            }
        }
        serde_json::Value::Array(items) => {
            for v in items {
                collect_priced(v, out);
            }
        }
        _ => {}
    }
}
