//! The protocol types decode the bytes this server actually serves.
//!
//! # Why this exists
//!
//! `RateValue` moved into `fusiform-protocol` so consumers could stop writing
//! their own decoders — and it did not describe the wire. ASTRO found it by
//! building against the crate: `missing field "amount"` on every priced rate,
//! because the type nested an `Amount` and the server serves those fields flat.
//!
//! The type was a DOMAIN type promoted to a wire type without anyone checking
//! that it described the wire, and nothing in this repository could notice. The
//! server never serializes through it: `json_rate` in fusiform-store hand-writes
//! the stored string and the serve path passes those bytes through. Two paths
//! answering "what is a rate on the wire", and no test compared them.
//!
//! The golden fixture could not catch it either, and that is the part worth
//! stating: it is generated BY the serve path, so it faithfully recorded bytes
//! the protocol type could not decode. Byte-identical across the move meant the
//! WIRE had not changed. It said nothing about whether the type matched.
//!
//! So this fence is the missing comparison: take the fixture the producer
//! generates, and decode it with the types a consumer compiles against.

use fusiform_protocol::money::{Floor, RateValue};

const SERVED: &str = include_str!("../fixtures/served-payloads.json");

/// Every priced rate in the served fixture decodes with the protocol type.
///
/// Driven from the FIXTURE rather than a literal, so a change to what the
/// server serves reaches this test without anyone remembering to update it —
/// which is the property the hand-copied literal in the original probe lacked.
#[test]
fn every_served_rate_decodes_with_the_protocol_type() {
    let doc: serde_json::Value = serde_json::from_str(SERVED).expect("the fixture parses");

    let mut rates = Vec::new();
    collect_priced(&doc, &mut rates);

    // NON-VACUITY: a fixture with no priced rates would pass the loop below
    // while proving nothing, which is the shape that let the original defect
    // through in the first place.
    assert!(
        !rates.is_empty(),
        "the fixture must contain priced rates, or this fence asserts nothing"
    );

    for raw in &rates {
        let decoded: Result<RateValue, _> = serde_json::from_value((*raw).clone());
        let value = decoded.unwrap_or_else(|e| {
            panic!(
                "the protocol type must decode what this server serves, and did \
                 not: {e}\n  served: {raw}\n\nA consumer compiling against \
                 fusiform-protocol reads exactly these bytes. If the type and \
                 the wire disagree, the crate that exists to remove hand-written \
                 decoders cannot replace one."
            )
        });

        match value {
            RateValue::Priced { amount, floor } => {
                assert!(
                    amount.units > 0,
                    "a priced rate must carry its units through the decode: {raw}"
                );
                // Absent from the wire today, so it must arrive as the state
                // that says nobody established it — never as no-minimum.
                assert_eq!(
                    floor,
                    Floor::Unknown,
                    "a rate served without a floor must decode as Unknown, not \
                     as an established absence: {raw}"
                );
            }
            other => panic!("a priced rate must decode as Priced, got {other:?}"),
        }
    }
}

fn collect_priced<'a>(node: &'a serde_json::Value, out: &mut Vec<&'a serde_json::Value>) {
    match node {
        serde_json::Value::Object(map) => {
            if map.get("state").and_then(|s| s.as_str()) == Some("priced") {
                out.push(node);
            }
            for v in map.values() {
                collect_priced(v, out);
            }
        }
        serde_json::Value::Array(items) => {
            for v in items {
                collect_priced(v, out);
            }
        }
        _ => {}
    }
}

/// Every variant the producer can WRITE decodes, not only the ones the fixture
/// happens to contain.
///
/// The fixture holds nine priced rates and no others, so the fence above — the
/// only loud thing on this seam — could not see `stated_zero` or `unpriced` at
/// all. Both decode today; that was measured rather than assumed, and it is
/// exactly the reasoning that produced the flatten defect, so it does not get
/// to stand on its own.
///
/// ASTRO made this load-bearing rather than tidy: since their deferred-catalog
/// change, a decode refusal on a priced rate is no longer a crash there. The
/// event stays `not_yet_priced` and their catalog reads healthy — quieter than
/// the old failure and worse for exactly that reason. A shape this fixture does
/// not contain would fail silently at the consumer and nowhere else.
///
/// The match is EXHAUSTIVE on purpose: a new `RateValue` variant fails to
/// compile here until someone states the bytes the producer writes for it. A
/// runtime list would simply not mention it.
#[test]
fn every_variant_the_producer_writes_decodes() {
    // Verbatim from `json_rate` in fusiform-store/src/ingest.rs, which is the
    // authority for what reaches the store and therefore the wire.
    let cases: &[(&str, &str)] = &[
        ("stated_zero", r#"{"state":"stated_zero"}"#),
        (
            "unpriced/missing_rate",
            r#"{"state":"unpriced","reason":"missing_rate"}"#,
        ),
        (
            "unpriced/no_catalog_coverage",
            r#"{"state":"unpriced","reason":"no_catalog_coverage"}"#,
        ),
        (
            "unpriced/unknown_charge_basis",
            r#"{"state":"unpriced","reason":"unknown_charge_basis"}"#,
        ),
    ];

    for (label, served) in cases {
        let decoded: RateValue = serde_json::from_str(served)
            .unwrap_or_else(|e| panic!("{label} must decode: {e}\n  served: {served}"));

        // Exhaustive: adding a variant breaks this until its bytes are stated.
        match decoded {
            RateValue::StatedZero => assert_eq!(*label, "stated_zero"),
            RateValue::Unpriced { .. } => assert!(label.starts_with("unpriced/")),
            RateValue::Priced { .. } => {
                panic!("{label} decoded as Priced, which would silently price a rate that is not")
            }
        }
    }

    // CONTROL: a shape the producer does NOT write must not decode, or the
    // assertions above would pass against a type that accepts anything.
    assert!(
        serde_json::from_str::<RateValue>(r#"{"state":"invented"}"#).is_err(),
        "an unknown state must refuse, else this fence proves nothing"
    );
}

/// Every key in a served rate must survive a round-trip through the published
/// type.
///
/// # The gap this closes
///
/// The tests above ask "does the wire DECODE", and serde answers yes while
/// silently dropping any field the type does not name. So a field can exist on
/// the wire, be load-bearing for a consumer, and be invisible to everyone
/// decoding through fusiform's own published types.
///
/// That is exactly what happened to `inherited_from`. It is injected as raw
/// JSON by the serve path and is not on `RateValue::Priced`, so a consumer
/// pinning from the FIXTURE BYTES sees the marker and a consumer decoding
/// through the TYPE does not — and the marker is the only thing distinguishing
/// a price this provider charges from one borrowed off another provider's card.
/// ALF reported their store collapsing that distinction; the type is why it was
/// easy to collapse.
///
/// Same family as the `amount` flatten defect ASTRO found: two paths answering
/// "what is a rate on the wire", never compared to each other. A decode test
/// cannot see it, because dropping unknown fields is decoding WORKING.
///
/// # Why round-trip rather than a field list
///
/// A list of expected keys is a second statement of the type, free to drift
/// from it. Re-serializing asks the type itself what it can carry, so the
/// assertion stays true as the type changes.
#[test]
fn no_served_rate_field_is_invisible_to_the_published_type() {
    let fixture: serde_json::Value =
        serde_json::from_str(SERVED).expect("the served fixture parses");

    let mut rates = Vec::new();
    collect_priced(&fixture, &mut rates);
    assert!(
        !rates.is_empty(),
        "no priced rates in the fixture would make this pass while proving \
         nothing"
    );

    let mut dropped: Vec<(String, Vec<String>)> = Vec::new();
    for raw in &rates {
        let Some(served) = raw.as_object() else {
            continue;
        };
        let decoded: RateValue = match serde_json::from_value((*raw).clone()) {
            Ok(v) => v,
            // Decode failures are the other tests' subject, not this one.
            Err(_) => continue,
        };
        let round_tripped = serde_json::to_value(&decoded).expect("the type re-serializes");
        let after = round_tripped
            .as_object()
            .expect("a rate re-serializes as an object");

        let lost: Vec<String> = served
            .keys()
            .filter(|k| !after.contains_key(*k))
            .cloned()
            .collect();
        if !lost.is_empty() {
            dropped.push((serde_json::to_string(raw).unwrap_or_default(), lost));
        }
    }

    assert!(
        dropped.is_empty(),
        "these fields are served on the wire and vanish when decoded through \
         the published type, so a consumer using fusiform's own types cannot \
         see them: {dropped:?}. Add them to the type or stop serving them — a \
         field that only exists in the bytes is one every typed consumer is \
         blind to."
    );
}

/// The fence above must be able to FAIL, proven on the field that motivated it.
///
/// The golden fixture contains no inherited rate — `inherited_from` is attached
/// at serve time to rows the fixture's store does not have — so the check runs
/// over rates that have nothing to lose and passes while seeing none of the
/// case it exists for. A fence whose only evidence is a clean run on data that
/// cannot dirty it is not a fence.
///
/// So the motivating shape is asserted directly, against the bytes the serve
/// path actually produces:
///
///     {"state":"priced","units":…,"exponent":9,"currency":"USD",
///      "inherited_from":{"provider_id":"zai","family":"glm",
///                        "basis":"open_weights"}}
///
/// This test is EXPECTED TO FAIL the day the type gains the field, and that is
/// the signal to delete it: its whole content is "the type does not carry this
/// yet, and here is the consequence".
#[test]
fn inherited_from_is_currently_invisible_to_the_published_type() {
    let served = serde_json::json!({
        "state": "priced",
        "units": 75_000_000i64,
        "exponent": 9,
        "currency": "USD",
        "unit_provenance": {
            "kind": "assumed_by_policy",
            "policy": "models-dev-usd-v1"
        },
        "inherited_from": {
            "provider_id": "zai",
            "family": "glm",
            "basis": "open_weights"
        }
    });

    let decoded: RateValue =
        serde_json::from_value(served.clone()).expect("an inherited rate decodes as priced");
    let round_tripped = serde_json::to_value(&decoded).expect("the type re-serializes");

    assert!(
        round_tripped.get("inherited_from").is_none(),
        "the type now carries inherited_from — DELETE THIS TEST, its subject is \
         gone, and the general fence above covers the field from here"
    );
    // Control: the round-trip preserves what the type DOES name, so the
    // assertion above is about a missing field rather than a broken decode.
    assert_eq!(
        round_tripped.get("units"),
        served.get("units"),
        "control: the fields the type names must survive the round-trip"
    );
}
