//! The protocol types decode the bytes this server actually serves.
//!
//! # Why this exists
//!
//! `RateValue` moved into `fusiform-protocol` so consumers could stop writing
//! their own decoders — and it did not describe the wire. ASTRO found it by
//! building against the crate: `missing field "amount"` on every priced rate,
//! because the type nested an `Amount` and the server serves those fields flat.
//!
//! The type was a DOMAIN type promoted to a wire type without anyone checking
//! that it described the wire, and nothing in this repository could notice. The
//! server never serializes through it: `json_rate` in fusiform-store hand-writes
//! the stored string and the serve path passes those bytes through. Two paths
//! answering "what is a rate on the wire", and no test compared them.
//!
//! The golden fixture could not catch it either, and that is the part worth
//! stating: it is generated BY the serve path, so it faithfully recorded bytes
//! the protocol type could not decode. Byte-identical across the move meant the
//! WIRE had not changed. It said nothing about whether the type matched.
//!
//! So this fence is the missing comparison: take the fixture the producer
//! generates, and decode it with the types a consumer compiles against.

use fusiform_protocol::money::{Floor, RateValue};

const SERVED: &str = include_str!("../fixtures/served-payloads.json");

/// Every priced rate in the served fixture decodes with the protocol type.
///
/// Driven from the FIXTURE rather than a literal, so a change to what the
/// server serves reaches this test without anyone remembering to update it —
/// which is the property the hand-copied literal in the original probe lacked.
#[test]
fn every_served_rate_decodes_with_the_protocol_type() {
    let doc: serde_json::Value = serde_json::from_str(SERVED).expect("the fixture parses");

    let mut rates = Vec::new();
    collect_priced(&doc, &mut rates);

    // NON-VACUITY: a fixture with no priced rates would pass the loop below
    // while proving nothing, which is the shape that let the original defect
    // through in the first place.
    assert!(
        !rates.is_empty(),
        "the fixture must contain priced rates, or this fence asserts nothing"
    );

    for raw in &rates {
        let decoded: Result<RateValue, _> = serde_json::from_value((*raw).clone());
        let value = decoded.unwrap_or_else(|e| {
            panic!(
                "the protocol type must decode what this server serves, and did \
                 not: {e}\n  served: {raw}\n\nA consumer compiling against \
                 fusiform-protocol reads exactly these bytes. If the type and \
                 the wire disagree, the crate that exists to remove hand-written \
                 decoders cannot replace one."
            )
        });

        match value {
            RateValue::Priced {
                amount,
                floor,
                inherited_from,
            } => {
                // Asserted where it is decoded rather than in a test of its
                // own: a marker that decodes to None on a row the producer
                // marked is the failure this whole file exists to catch, and
                // it is invisible unless something reads it here.
                if raw.get("inherited_from").is_some() {
                    assert!(
                        inherited_from.is_some(),
                        "the wire carries inherited_from and the type decoded \
                         None: {raw}"
                    );
                }
                // Same property one level down: an alias marker names the
                // target's model id, and a type that dropped it would leave a
                // consumer unable to tell whose row the price came from.
                if let Some(model_id) = raw["inherited_from"].get("model_id") {
                    assert_eq!(
                        inherited_from.as_ref().and_then(|i| i.model_id.as_deref()),
                        model_id.as_str(),
                        "the wire carries inherited_from.model_id and the type \
                         did not decode it: {raw}"
                    );
                }
                assert!(
                    amount.units > 0,
                    "a priced rate must carry its units through the decode: {raw}"
                );
                // Absent from the wire today, so it must arrive as the state
                // that says nobody established it — never as no-minimum.
                assert_eq!(
                    floor,
                    Floor::Unknown,
                    "a rate served without a floor must decode as Unknown, not \
                     as an established absence: {raw}"
                );
            }
            other => panic!("a priced rate must decode as Priced, got {other:?}"),
        }
    }
}

fn collect_priced<'a>(node: &'a serde_json::Value, out: &mut Vec<&'a serde_json::Value>) {
    match node {
        serde_json::Value::Object(map) => {
            if map.get("state").and_then(|s| s.as_str()) == Some("priced") {
                out.push(node);
            }
            for v in map.values() {
                collect_priced(v, out);
            }
        }
        serde_json::Value::Array(items) => {
            for v in items {
                collect_priced(v, out);
            }
        }
        _ => {}
    }
}

/// Every variant the producer can WRITE decodes, not only the ones the fixture
/// happens to contain.
///
/// The fixture held nine priced rates and no others when this was written, so
/// the fence above — the only loud thing on this seam — could not see
/// `stated_zero` or `unpriced` at all. Both decode today; that was measured
/// rather than assumed, and it is exactly the reasoning that produced the
/// flatten defect, so it does not get to stand on its own.
///
/// # These literals are my belief about the producer, so two of them are checked
///
/// A hand-written literal pins what I BELIEVE `json_rate` emits. The fixture
/// pins what it ACTUALLY emits, and the two can drift apart silently — this
/// test would keep passing against bytes no producer writes.
///
/// The fixture now carries `stated_zero` and `unpriced/missing_rate` in real
/// served bytes, so those two literals are asserted byte-identical to what the
/// fixture contains. The other two have no producer path reachable from the
/// fixture's store and stay unchecked, which is stated rather than hidden:
///
///     no_catalog_coverage    written where a model is described with no cost
///                            object at all, which serves NO RATE FACTS rather
///                            than an unpriced one
///     unknown_charge_basis   written for a cost key the parser has no charge
///                            unit for, such as audio, absent from the excerpt
///
/// ASTRO made this load-bearing rather than tidy: since their deferred-catalog
/// change, a decode refusal on a priced rate is no longer a crash there. The
/// event stays `not_yet_priced` and their catalog reads healthy — quieter than
/// the old failure and worse for exactly that reason. A shape this fixture does
/// not contain would fail silently at the consumer and nowhere else.
///
/// The match is EXHAUSTIVE on purpose: a new `RateValue` variant fails to
/// compile here until someone states the bytes the producer writes for it. A
/// runtime list would simply not mention it.
#[test]
fn every_variant_the_producer_writes_decodes() {
    // Verbatim from `json_rate` in fusiform-store/src/ingest.rs, which is the
    // authority for what reaches the store and therefore the wire.
    let cases: &[(&str, &str)] = &[
        ("stated_zero", r#"{"state":"stated_zero"}"#),
        (
            "unpriced/missing_rate",
            r#"{"state":"unpriced","reason":"missing_rate"}"#,
        ),
        (
            "unpriced/no_catalog_coverage",
            r#"{"state":"unpriced","reason":"no_catalog_coverage"}"#,
        ),
        (
            "unpriced/unknown_charge_basis",
            r#"{"state":"unpriced","reason":"unknown_charge_basis"}"#,
        ),
    ];

    // What the producer ACTUALLY wrote, collected from the fixture's served
    // bytes so a literal below can be checked rather than trusted.
    let fixture: serde_json::Value = serde_json::from_str(SERVED).expect("the fixture parses");
    let mut produced: Vec<String> = Vec::new();
    collect_rate_shapes(&fixture, &mut produced);
    assert!(
        !produced.is_empty(),
        "the fixture must contain served rates, or the cross-check below passes \
         vacuously and this fence is back to trusting its own literals"
    );

    for (label, served) in cases {
        let decoded: RateValue = serde_json::from_str(served)
            .unwrap_or_else(|e| panic!("{label} must decode: {e}\n  served: {served}"));

        // CROSS-CHECK where the fixture can reach: the literal must be exactly
        // what the producer wrote, not merely something that decodes.
        let state = decoded_state(served);
        // Keyed on state AND reason, not on state alone. My first version
        // grouped by state, so `unpriced/no_catalog_coverage` was compared
        // against the fixture's `unpriced/missing_rate` and fired — a
        // comparison over a population broader than the claim, which is the
        // same defect this fence exists to catch, one level up.
        let literal = canonical_str(served);
        let same_kind: Vec<&String> = produced
            .iter()
            .filter(|p| decoded_state(p) == state && decoded_reason(p) == decoded_reason(served))
            .collect();
        if !same_kind.is_empty() {
            assert!(
                same_kind.iter().any(|p| p.as_str() == literal),
                "{label}: this literal is not what the producer writes.\n  \
                 literal:  {served}\n  fixture:  {:?}\n\
                 Either json_rate changed and this literal is stale, or the \
                 literal was wrong from the start — and a stale literal keeps \
                 this fence green while testing bytes nobody serves.",
                same_kind
            );
        }

        // Exhaustive: adding a variant breaks this until its bytes are stated.
        match decoded {
            RateValue::StatedZero { .. } => assert_eq!(*label, "stated_zero"),
            RateValue::Unpriced { .. } => assert!(label.starts_with("unpriced/")),
            RateValue::Priced { .. } => {
                panic!("{label} decoded as Priced, which would silently price a rate that is not")
            }
        }
    }

    // CONTROL: a shape the producer does NOT write must not decode, or the
    // assertions above would pass against a type that accepts anything.
    assert!(
        serde_json::from_str::<RateValue>(r#"{"state":"invented"}"#).is_err(),
        "an unknown state must refuse, else this fence proves nothing"
    );
}

/// Every key in a served rate must survive a round-trip through the published
/// type.
///
/// # The gap this closes
///
/// The tests above ask "does the wire DECODE", and serde answers yes while
/// silently dropping any field the type does not name. So a field can exist on
/// the wire, be load-bearing for a consumer, and be invisible to everyone
/// decoding through fusiform's own published types.
///
/// That is exactly what happened to `inherited_from`. It is injected as raw
/// JSON by the serve path and is not on `RateValue::Priced`, so a consumer
/// pinning from the FIXTURE BYTES sees the marker and a consumer decoding
/// through the TYPE does not — and the marker is the only thing distinguishing
/// a price this provider charges from one borrowed off another provider's card.
/// ALF reported their store collapsing that distinction; the type is why it was
/// easy to collapse.
///
/// Same family as the `amount` flatten defect ASTRO found: two paths answering
/// "what is a rate on the wire", never compared to each other. A decode test
/// cannot see it, because dropping unknown fields is decoding WORKING.
///
/// # Why round-trip rather than a field list
///
/// A list of expected keys is a second statement of the type, free to drift
/// from it. Re-serializing asks the type itself what it can carry, so the
/// assertion stays true as the type changes.
#[test]
fn no_served_rate_field_is_invisible_to_the_published_type() {
    let fixture: serde_json::Value =
        serde_json::from_str(SERVED).expect("the served fixture parses");

    let mut rates = Vec::new();
    collect_priced(&fixture, &mut rates);
    assert!(
        !rates.is_empty(),
        "no priced rates in the fixture would make this pass while proving \
         nothing"
    );

    let mut dropped: Vec<(String, Vec<String>)> = Vec::new();
    for raw in &rates {
        let Some(served) = raw.as_object() else {
            continue;
        };
        let decoded: RateValue = match serde_json::from_value((*raw).clone()) {
            Ok(v) => v,
            // Decode failures are the other tests' subject, not this one.
            Err(_) => continue,
        };
        let round_tripped = serde_json::to_value(&decoded).expect("the type re-serializes");
        let after = round_tripped
            .as_object()
            .expect("a rate re-serializes as an object");

        let lost: Vec<String> = served
            .keys()
            .filter(|k| !after.contains_key(*k))
            .cloned()
            .collect();
        if !lost.is_empty() {
            dropped.push((serde_json::to_string(raw).unwrap_or_default(), lost));
        }
    }

    assert!(
        dropped.is_empty(),
        "these fields are served on the wire and vanish when decoded through \
         the published type, so a consumer using fusiform's own types cannot \
         see them: {dropped:?}. Add them to the type or stop serving them — a \
         field that only exists in the bytes is one every typed consumer is \
         blind to."
    );
}

/// A borrowed marker survives the published type in EVERY rate state.
///
/// The test above walks priced rates only, and the marker is not a priced-rate
/// property: inheritance and aliases attach it to whatever state the other row
/// published, `stated_zero` included. When only `Priced` named the field, a
/// borrowed zero decoded as this provider stating the model is free — the
/// published/borrowed collapse the marker exists to prevent, one state over.
///
/// Requires the fixture to carry a non-priced borrowed rate, so the walk
/// below cannot pass by finding only the priced ones the older fence covers.
#[test]
fn a_borrowed_marker_survives_the_published_type_in_every_state() {
    let fixture: serde_json::Value =
        serde_json::from_str(SERVED).expect("the served fixture parses");
    let mut shapes: Vec<String> = Vec::new();
    collect_rate_shapes(&fixture, &mut shapes);

    let marked: Vec<serde_json::Value> = shapes
        .iter()
        .map(|s| serde_json::from_str::<serde_json::Value>(s).expect("a shape parses"))
        .filter(|v| v.get("inherited_from").is_some())
        .collect();
    assert!(
        marked.iter().any(|v| v["state"] == "stated_zero"),
        "the fixture must carry a borrowed stated_zero, or this fence checks \
         only the priced state the older test already covers: {marked:?}"
    );

    let mut lost: Vec<String> = Vec::new();
    for served in &marked {
        let decoded: RateValue = serde_json::from_value(served.clone())
            .unwrap_or_else(|e| panic!("a served rate must decode: {e}\n  {served}"));
        let back = serde_json::to_value(&decoded).expect("the type re-serializes");
        if back.get("inherited_from") != served.get("inherited_from") {
            lost.push(served.to_string());
        }
    }
    assert!(
        lost.is_empty(),
        "these served rates carry inherited_from and the published type does \
         not carry it through, so a typed consumer reads a borrowed value as \
         this provider's own statement: {lost:?}"
    );
}

/// The `reason` field of a served rate, or `""` if absent.
fn decoded_reason(served: &str) -> String {
    serde_json::from_str::<serde_json::Value>(served)
        .ok()
        .and_then(|v| v["reason"].as_str().map(str::to_string))
        .unwrap_or_default()
}

/// The `state` field of a served rate, or `""` if absent.
fn decoded_state(served: &str) -> String {
    serde_json::from_str::<serde_json::Value>(served)
        .ok()
        .and_then(|v| v["state"].as_str().map(str::to_string))
        .unwrap_or_default()
}

/// Every served rate object in the fixture, serialised back to compact JSON.
///
/// Walks rather than indexing known paths: a rate can appear under any model in
/// any case, and a walker that misses one would narrow the comparison set
/// silently — which reads as "the literal matched" rather than as "nothing was
/// compared".
fn collect_rate_shapes(value: &serde_json::Value, out: &mut Vec<String>) {
    match value {
        serde_json::Value::Object(map) => {
            // A rate object is the one carrying `state`. Serialised with the
            // same compact form the literals use so the comparison is on
            // content rather than on whitespace.
            if map.contains_key("state") {
                out.push(canonical(value));
            }
            for v in map.values() {
                collect_rate_shapes(v, out);
            }
        }
        serde_json::Value::Array(items) => {
            for v in items {
                collect_rate_shapes(v, out);
            }
        }
        _ => {}
    }
}

/// A rate object serialised with its keys SORTED.
///
/// Key-sorted rather than as-written, because my first version compared raw
/// serialisations and fired on `{"reason":..,"state":..}` against
/// `{"state":..,"reason":..}` — identical documents in different key order.
/// JSON objects are unordered, so that difference is not drift, and comparing
/// it makes the check fail on a property no contract holds.
///
/// What it still catches, which is the whole point: a field the producer writes
/// and the literal omits, a field the literal invents, or any value that
/// differs.
fn canonical(v: &serde_json::Value) -> String {
    let mut map = std::collections::BTreeMap::new();
    if let serde_json::Value::Object(o) = v {
        for (k, val) in o {
            map.insert(k.clone(), val.clone());
        }
    }
    serde_json::to_string(&map).expect("a served rate serialises")
}

/// `canonical` for a literal that has not been parsed yet.
fn canonical_str(served: &str) -> String {
    canonical(&serde_json::from_str(served).expect("a literal in this test parses"))
}

/// The fixture carries a real served example of every `RateValue` state.
///
/// # This is the half of the consolidation risk that CAN be fenced
///
/// The coverage fences in `golden_payload.rs` are key-level: they ask whether
/// `rate.input` appears, not whether its VALUE reached each shape a consumer
/// must decode. So folding cases together keeps them green while the shapes
/// stop being separately pinned — ASTRO and I both concluded that was
/// comment-only and put warnings at the point of temptation.
///
/// For rate states it is not comment-only. The vocabulary is a closed enum, so
/// the question "did every state reach the fixture" has an exhaustive answer,
/// and this asks it.
///
/// # Why this vocabulary and not another
///
/// It is the one that actually bit. The fixture carried `priced` and nothing
/// else until 2026-09-19, so a consumer pinning from it would never have met
/// `stated_zero` or `unpriced` — and those three are not interchangeable: a
/// number, a provider saying a dimension is FREE, and nobody having published
/// one. A decoder that collapses them bills nothing for a rate the upstream
/// withdrew.
///
/// # Exhaustive on purpose
///
/// A new variant fails to compile here until someone states whether the fixture
/// must carry an example. A runtime list would simply not mention it, which is
/// how `stated_zero` went unpinned for a month.
#[test]
fn the_fixture_carries_every_rate_state() {
    let doc: serde_json::Value = serde_json::from_str(SERVED).expect("the fixture parses");
    let mut shapes: Vec<String> = Vec::new();
    collect_rate_shapes(&doc, &mut shapes);
    assert!(
        !shapes.is_empty(),
        "no served rates found at all, so every assertion below would pass \
         against a fixture carrying nothing"
    );

    let mut seen_priced = false;
    let mut seen_stated_zero = false;
    let mut seen_unpriced = false;
    for shape in &shapes {
        match serde_json::from_str::<RateValue>(shape) {
            Ok(RateValue::Priced { .. }) => seen_priced = true,
            Ok(RateValue::StatedZero { .. }) => seen_stated_zero = true,
            Ok(RateValue::Unpriced { .. }) => seen_unpriced = true,
            // A served rate that does not decode is the flatten defect, and the
            // fence above this one is what reports it. Ignored here so this test
            // answers its own question rather than two.
            Err(_) => {}
        }
    }

    let missing: Vec<&str> = [
        ("priced", seen_priced),
        ("stated_zero", seen_stated_zero),
        ("unpriced", seen_unpriced),
    ]
    .iter()
    .filter(|(_, seen)| !seen)
    .map(|(name, _)| *name)
    .collect();

    assert!(
        missing.is_empty(),
        "\n\nThe fixture carries no served example of: {missing:?}\n\n\
         These states are NOT interchangeable -- a number, a provider saying a \
         dimension is free, and nobody having published one -- and a consumer \
         pinning from this fixture never meets the missing one.\n\n\
         Add a case to golden_payload.rs that PRODUCES it. A model with a zero \
         in its cost object gives stated_zero; a withdrawn rate gives \
         unpriced/missing_rate.\n\n\
         Found {} served rates in total.\n",
        shapes.len()
    );
}
